/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoreIndexRouteImport } from './routes/_store.index'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as StoreTrocasEDevolucoesRouteImport } from './routes/_store.trocas-e-devolucoes'
import { Route as StoreTermosRouteImport } from './routes/_store.termos'
import { Route as StoreStoriesRouteImport } from './routes/_store.stories'
import { Route as StoreRecuperarSenhaRouteImport } from './routes/_store.recuperar-senha'
import { Route as StorePromocoesRouteImport } from './routes/_store.promocoes'
import { Route as StorePrivacidadeRouteImport } from './routes/_store.privacidade'
import { Route as StorePerfilDaLojaRouteImport } from './routes/_store.perfil-da-loja'
import { Route as StoreLinksRouteImport } from './routes/_store.links'
import { Route as StoreInstalarRouteImport } from './routes/_store.instalar'
import { Route as StoreFaqRouteImport } from './routes/_store.faq'
import { Route as StoreEntrarRouteImport } from './routes/_store.entrar'
import { Route as StoreContatoRouteImport } from './routes/_store.contato'
import { Route as StoreContaRouteImport } from './routes/_store.conta'
import { Route as StoreCatalogoRouteImport } from './routes/_store.catalogo'
import { Route as StoreCarrinhoRouteImport } from './routes/_store.carrinho'
import { Route as StoreCadastroRouteImport } from './routes/_store.cadastro'
import { Route as StoreBuscarRouteImport } from './routes/_store.buscar'
import { Route as StoreContaIndexRouteImport } from './routes/_store.conta.index'
import { Route as AdminConfiguracoesLojaRouteImport } from './routes/admin.configuracoes.loja'
import { Route as StoreProdutoSlugRouteImport } from './routes/_store.produto.$slug'
import { Route as StorePoliticasSlugRouteImport } from './routes/_store.politicas.$slug'
import { Route as StoreGiftCardClaimTokenRouteImport } from './routes/_store.gift-card.$claimToken'
import { Route as StoreDestaquesSlugRouteImport } from './routes/_store.destaques.$slug'
import { Route as StoreContaTrocasRouteImport } from './routes/_store.conta.trocas'
import { Route as StoreContaSuporteRouteImport } from './routes/_store.conta.suporte'
import { Route as StoreContaPrivacidadeRouteImport } from './routes/_store.conta.privacidade'
import { Route as StoreContaPerfilRouteImport } from './routes/_store.conta.perfil'
import { Route as StoreContaPedidosRouteImport } from './routes/_store.conta.pedidos'
import { Route as StoreContaPagamentosRouteImport } from './routes/_store.conta.pagamentos'
import { Route as StoreContaGiftCardsRouteImport } from './routes/_store.conta.gift-cards'
import { Route as StoreContaEnderecosRouteImport } from './routes/_store.conta.enderecos'
import { Route as StoreContaCreditosRouteImport } from './routes/_store.conta.creditos'
import { Route as StoreContaAvaliacoesRouteImport } from './routes/_store.conta.avaliacoes'
import { Route as StoreColecaoSlugRouteImport } from './routes/_store.colecao.$slug'
import { Route as StoreCheckoutRevisaoRouteImport } from './routes/_store.checkout.revisao'
import { Route as StoreCheckoutPagamentoRouteImport } from './routes/_store.checkout.pagamento'
import { Route as StoreCheckoutIdentificacaoRouteImport } from './routes/_store.checkout.identificacao'
import { Route as StoreCheckoutEntregaRouteImport } from './routes/_store.checkout.entrega'
import { Route as StoreCheckoutCotacaoRouteImport } from './routes/_store.checkout.cotacao'
import { Route as StoreCategoriaSlugRouteImport } from './routes/_store.categoria.$slug'
import { Route as StorePedidoPublicTokenConfirmacaoRouteImport } from './routes/_store.pedido.$publicToken.confirmacao'
import { Route as StoreContaPedidosIdRouteImport } from './routes/_store.conta.pedidos.$id'
import { Route as StoreContaConversasIdRouteImport } from './routes/_store.conta.conversas.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const StoreTrocasEDevolucoesRoute = StoreTrocasEDevolucoesRouteImport.update({
  id: '/trocas-e-devolucoes',
  path: '/trocas-e-devolucoes',
  getParentRoute: () => StoreRoute,
} as any)
const StoreTermosRoute = StoreTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => StoreRoute,
} as any)
const StoreStoriesRoute = StoreStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRecuperarSenhaRoute = StoreRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => StoreRoute,
} as any)
const StorePromocoesRoute = StorePromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => StoreRoute,
} as any)
const StorePrivacidadeRoute = StorePrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => StoreRoute,
} as any)
const StorePerfilDaLojaRoute = StorePerfilDaLojaRouteImport.update({
  id: '/perfil-da-loja',
  path: '/perfil-da-loja',
  getParentRoute: () => StoreRoute,
} as any)
const StoreLinksRoute = StoreLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => StoreRoute,
} as any)
const StoreInstalarRoute = StoreInstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => StoreRoute,
} as any)
const StoreFaqRoute = StoreFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => StoreRoute,
} as any)
const StoreEntrarRoute = StoreEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContatoRoute = StoreContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContaRoute = StoreContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCatalogoRoute = StoreCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCarrinhoRoute = StoreCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCadastroRoute = StoreCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => StoreRoute,
} as any)
const StoreBuscarRoute = StoreBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContaIndexRoute = StoreContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreContaRoute,
} as any)
const AdminConfiguracoesLojaRoute = AdminConfiguracoesLojaRouteImport.update({
  id: '/configuracoes/loja',
  path: '/configuracoes/loja',
  getParentRoute: () => AdminRoute,
} as any)
const StoreProdutoSlugRoute = StoreProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StorePoliticasSlugRoute = StorePoliticasSlugRouteImport.update({
  id: '/politicas/$slug',
  path: '/politicas/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreGiftCardClaimTokenRoute = StoreGiftCardClaimTokenRouteImport.update({
  id: '/gift-card/$claimToken',
  path: '/gift-card/$claimToken',
  getParentRoute: () => StoreRoute,
} as any)
const StoreDestaquesSlugRoute = StoreDestaquesSlugRouteImport.update({
  id: '/destaques/$slug',
  path: '/destaques/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContaTrocasRoute = StoreContaTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaSuporteRoute = StoreContaSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPrivacidadeRoute = StoreContaPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPerfilRoute = StoreContaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPedidosRoute = StoreContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPagamentosRoute = StoreContaPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaGiftCardsRoute = StoreContaGiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaEnderecosRoute = StoreContaEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaCreditosRoute = StoreContaCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaAvaliacoesRoute = StoreContaAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreColecaoSlugRoute = StoreColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRevisaoRoute = StoreCheckoutRevisaoRouteImport.update({
  id: '/checkout/revisao',
  path: '/checkout/revisao',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutPagamentoRoute = StoreCheckoutPagamentoRouteImport.update({
  id: '/checkout/pagamento',
  path: '/checkout/pagamento',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutIdentificacaoRoute =
  StoreCheckoutIdentificacaoRouteImport.update({
    id: '/checkout/identificacao',
    path: '/checkout/identificacao',
    getParentRoute: () => StoreRoute,
  } as any)
const StoreCheckoutEntregaRoute = StoreCheckoutEntregaRouteImport.update({
  id: '/checkout/entrega',
  path: '/checkout/entrega',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutCotacaoRoute = StoreCheckoutCotacaoRouteImport.update({
  id: '/checkout/cotacao',
  path: '/checkout/cotacao',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCategoriaSlugRoute = StoreCategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StorePedidoPublicTokenConfirmacaoRoute =
  StorePedidoPublicTokenConfirmacaoRouteImport.update({
    id: '/pedido/$publicToken/confirmacao',
    path: '/pedido/$publicToken/confirmacao',
    getParentRoute: () => StoreRoute,
  } as any)
const StoreContaPedidosIdRoute = StoreContaPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoreContaPedidosRoute,
} as any)
const StoreContaConversasIdRoute = StoreContaConversasIdRouteImport.update({
  id: '/conversas/$id',
  path: '/conversas/$id',
  getParentRoute: () => StoreContaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buscar': typeof StoreBuscarRoute
  '/cadastro': typeof StoreCadastroRoute
  '/carrinho': typeof StoreCarrinhoRoute
  '/catalogo': typeof StoreCatalogoRoute
  '/conta': typeof StoreContaRouteWithChildren
  '/contato': typeof StoreContatoRoute
  '/entrar': typeof StoreEntrarRoute
  '/faq': typeof StoreFaqRoute
  '/instalar': typeof StoreInstalarRoute
  '/links': typeof StoreLinksRoute
  '/perfil-da-loja': typeof StorePerfilDaLojaRoute
  '/privacidade': typeof StorePrivacidadeRoute
  '/promocoes': typeof StorePromocoesRoute
  '/recuperar-senha': typeof StoreRecuperarSenhaRoute
  '/stories': typeof StoreStoriesRoute
  '/termos': typeof StoreTermosRoute
  '/trocas-e-devolucoes': typeof StoreTrocasEDevolucoesRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/': typeof AdminIndexRoute
  '/categoria/$slug': typeof StoreCategoriaSlugRoute
  '/checkout/cotacao': typeof StoreCheckoutCotacaoRoute
  '/checkout/entrega': typeof StoreCheckoutEntregaRoute
  '/checkout/identificacao': typeof StoreCheckoutIdentificacaoRoute
  '/checkout/pagamento': typeof StoreCheckoutPagamentoRoute
  '/checkout/revisao': typeof StoreCheckoutRevisaoRoute
  '/colecao/$slug': typeof StoreColecaoSlugRoute
  '/conta/avaliacoes': typeof StoreContaAvaliacoesRoute
  '/conta/creditos': typeof StoreContaCreditosRoute
  '/conta/enderecos': typeof StoreContaEnderecosRoute
  '/conta/gift-cards': typeof StoreContaGiftCardsRoute
  '/conta/pagamentos': typeof StoreContaPagamentosRoute
  '/conta/pedidos': typeof StoreContaPedidosRouteWithChildren
  '/conta/perfil': typeof StoreContaPerfilRoute
  '/conta/privacidade': typeof StoreContaPrivacidadeRoute
  '/conta/suporte': typeof StoreContaSuporteRoute
  '/conta/trocas': typeof StoreContaTrocasRoute
  '/destaques/$slug': typeof StoreDestaquesSlugRoute
  '/gift-card/$claimToken': typeof StoreGiftCardClaimTokenRoute
  '/politicas/$slug': typeof StorePoliticasSlugRoute
  '/produto/$slug': typeof StoreProdutoSlugRoute
  '/admin/configuracoes/loja': typeof AdminConfiguracoesLojaRoute
  '/conta/': typeof StoreContaIndexRoute
  '/conta/conversas/$id': typeof StoreContaConversasIdRoute
  '/conta/pedidos/$id': typeof StoreContaPedidosIdRoute
  '/pedido/$publicToken/confirmacao': typeof StorePedidoPublicTokenConfirmacaoRoute
}
export interface FileRoutesByTo {
  '/buscar': typeof StoreBuscarRoute
  '/cadastro': typeof StoreCadastroRoute
  '/carrinho': typeof StoreCarrinhoRoute
  '/catalogo': typeof StoreCatalogoRoute
  '/contato': typeof StoreContatoRoute
  '/entrar': typeof StoreEntrarRoute
  '/faq': typeof StoreFaqRoute
  '/instalar': typeof StoreInstalarRoute
  '/links': typeof StoreLinksRoute
  '/perfil-da-loja': typeof StorePerfilDaLojaRoute
  '/privacidade': typeof StorePrivacidadeRoute
  '/promocoes': typeof StorePromocoesRoute
  '/recuperar-senha': typeof StoreRecuperarSenhaRoute
  '/stories': typeof StoreStoriesRoute
  '/termos': typeof StoreTermosRoute
  '/trocas-e-devolucoes': typeof StoreTrocasEDevolucoesRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminIndexRoute
  '/categoria/$slug': typeof StoreCategoriaSlugRoute
  '/checkout/cotacao': typeof StoreCheckoutCotacaoRoute
  '/checkout/entrega': typeof StoreCheckoutEntregaRoute
  '/checkout/identificacao': typeof StoreCheckoutIdentificacaoRoute
  '/checkout/pagamento': typeof StoreCheckoutPagamentoRoute
  '/checkout/revisao': typeof StoreCheckoutRevisaoRoute
  '/colecao/$slug': typeof StoreColecaoSlugRoute
  '/conta/avaliacoes': typeof StoreContaAvaliacoesRoute
  '/conta/creditos': typeof StoreContaCreditosRoute
  '/conta/enderecos': typeof StoreContaEnderecosRoute
  '/conta/gift-cards': typeof StoreContaGiftCardsRoute
  '/conta/pagamentos': typeof StoreContaPagamentosRoute
  '/conta/pedidos': typeof StoreContaPedidosRouteWithChildren
  '/conta/perfil': typeof StoreContaPerfilRoute
  '/conta/privacidade': typeof StoreContaPrivacidadeRoute
  '/conta/suporte': typeof StoreContaSuporteRoute
  '/conta/trocas': typeof StoreContaTrocasRoute
  '/destaques/$slug': typeof StoreDestaquesSlugRoute
  '/gift-card/$claimToken': typeof StoreGiftCardClaimTokenRoute
  '/politicas/$slug': typeof StorePoliticasSlugRoute
  '/produto/$slug': typeof StoreProdutoSlugRoute
  '/admin/configuracoes/loja': typeof AdminConfiguracoesLojaRoute
  '/conta': typeof StoreContaIndexRoute
  '/conta/conversas/$id': typeof StoreContaConversasIdRoute
  '/conta/pedidos/$id': typeof StoreContaPedidosIdRoute
  '/pedido/$publicToken/confirmacao': typeof StorePedidoPublicTokenConfirmacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_store/buscar': typeof StoreBuscarRoute
  '/_store/cadastro': typeof StoreCadastroRoute
  '/_store/carrinho': typeof StoreCarrinhoRoute
  '/_store/catalogo': typeof StoreCatalogoRoute
  '/_store/conta': typeof StoreContaRouteWithChildren
  '/_store/contato': typeof StoreContatoRoute
  '/_store/entrar': typeof StoreEntrarRoute
  '/_store/faq': typeof StoreFaqRoute
  '/_store/instalar': typeof StoreInstalarRoute
  '/_store/links': typeof StoreLinksRoute
  '/_store/perfil-da-loja': typeof StorePerfilDaLojaRoute
  '/_store/privacidade': typeof StorePrivacidadeRoute
  '/_store/promocoes': typeof StorePromocoesRoute
  '/_store/recuperar-senha': typeof StoreRecuperarSenhaRoute
  '/_store/stories': typeof StoreStoriesRoute
  '/_store/termos': typeof StoreTermosRoute
  '/_store/trocas-e-devolucoes': typeof StoreTrocasEDevolucoesRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/_store/': typeof StoreIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_store/categoria/$slug': typeof StoreCategoriaSlugRoute
  '/_store/checkout/cotacao': typeof StoreCheckoutCotacaoRoute
  '/_store/checkout/entrega': typeof StoreCheckoutEntregaRoute
  '/_store/checkout/identificacao': typeof StoreCheckoutIdentificacaoRoute
  '/_store/checkout/pagamento': typeof StoreCheckoutPagamentoRoute
  '/_store/checkout/revisao': typeof StoreCheckoutRevisaoRoute
  '/_store/colecao/$slug': typeof StoreColecaoSlugRoute
  '/_store/conta/avaliacoes': typeof StoreContaAvaliacoesRoute
  '/_store/conta/creditos': typeof StoreContaCreditosRoute
  '/_store/conta/enderecos': typeof StoreContaEnderecosRoute
  '/_store/conta/gift-cards': typeof StoreContaGiftCardsRoute
  '/_store/conta/pagamentos': typeof StoreContaPagamentosRoute
  '/_store/conta/pedidos': typeof StoreContaPedidosRouteWithChildren
  '/_store/conta/perfil': typeof StoreContaPerfilRoute
  '/_store/conta/privacidade': typeof StoreContaPrivacidadeRoute
  '/_store/conta/suporte': typeof StoreContaSuporteRoute
  '/_store/conta/trocas': typeof StoreContaTrocasRoute
  '/_store/destaques/$slug': typeof StoreDestaquesSlugRoute
  '/_store/gift-card/$claimToken': typeof StoreGiftCardClaimTokenRoute
  '/_store/politicas/$slug': typeof StorePoliticasSlugRoute
  '/_store/produto/$slug': typeof StoreProdutoSlugRoute
  '/admin/configuracoes/loja': typeof AdminConfiguracoesLojaRoute
  '/_store/conta/': typeof StoreContaIndexRoute
  '/_store/conta/conversas/$id': typeof StoreContaConversasIdRoute
  '/_store/conta/pedidos/$id': typeof StoreContaPedidosIdRoute
  '/_store/pedido/$publicToken/confirmacao': typeof StorePedidoPublicTokenConfirmacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/conta'
    | '/contato'
    | '/entrar'
    | '/faq'
    | '/instalar'
    | '/links'
    | '/perfil-da-loja'
    | '/privacidade'
    | '/promocoes'
    | '/recuperar-senha'
    | '/stories'
    | '/termos'
    | '/trocas-e-devolucoes'
    | '/admin/onboarding'
    | '/admin/'
    | '/categoria/$slug'
    | '/checkout/cotacao'
    | '/checkout/entrega'
    | '/checkout/identificacao'
    | '/checkout/pagamento'
    | '/checkout/revisao'
    | '/colecao/$slug'
    | '/conta/avaliacoes'
    | '/conta/creditos'
    | '/conta/enderecos'
    | '/conta/gift-cards'
    | '/conta/pagamentos'
    | '/conta/pedidos'
    | '/conta/perfil'
    | '/conta/privacidade'
    | '/conta/suporte'
    | '/conta/trocas'
    | '/destaques/$slug'
    | '/gift-card/$claimToken'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/admin/configuracoes/loja'
    | '/conta/'
    | '/conta/conversas/$id'
    | '/conta/pedidos/$id'
    | '/pedido/$publicToken/confirmacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/contato'
    | '/entrar'
    | '/faq'
    | '/instalar'
    | '/links'
    | '/perfil-da-loja'
    | '/privacidade'
    | '/promocoes'
    | '/recuperar-senha'
    | '/stories'
    | '/termos'
    | '/trocas-e-devolucoes'
    | '/admin/onboarding'
    | '/'
    | '/admin'
    | '/categoria/$slug'
    | '/checkout/cotacao'
    | '/checkout/entrega'
    | '/checkout/identificacao'
    | '/checkout/pagamento'
    | '/checkout/revisao'
    | '/colecao/$slug'
    | '/conta/avaliacoes'
    | '/conta/creditos'
    | '/conta/enderecos'
    | '/conta/gift-cards'
    | '/conta/pagamentos'
    | '/conta/pedidos'
    | '/conta/perfil'
    | '/conta/privacidade'
    | '/conta/suporte'
    | '/conta/trocas'
    | '/destaques/$slug'
    | '/gift-card/$claimToken'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/admin/configuracoes/loja'
    | '/conta'
    | '/conta/conversas/$id'
    | '/conta/pedidos/$id'
    | '/pedido/$publicToken/confirmacao'
  id:
    | '__root__'
    | '/_store'
    | '/admin'
    | '/_store/buscar'
    | '/_store/cadastro'
    | '/_store/carrinho'
    | '/_store/catalogo'
    | '/_store/conta'
    | '/_store/contato'
    | '/_store/entrar'
    | '/_store/faq'
    | '/_store/instalar'
    | '/_store/links'
    | '/_store/perfil-da-loja'
    | '/_store/privacidade'
    | '/_store/promocoes'
    | '/_store/recuperar-senha'
    | '/_store/stories'
    | '/_store/termos'
    | '/_store/trocas-e-devolucoes'
    | '/admin/onboarding'
    | '/_store/'
    | '/admin/'
    | '/_store/categoria/$slug'
    | '/_store/checkout/cotacao'
    | '/_store/checkout/entrega'
    | '/_store/checkout/identificacao'
    | '/_store/checkout/pagamento'
    | '/_store/checkout/revisao'
    | '/_store/colecao/$slug'
    | '/_store/conta/avaliacoes'
    | '/_store/conta/creditos'
    | '/_store/conta/enderecos'
    | '/_store/conta/gift-cards'
    | '/_store/conta/pagamentos'
    | '/_store/conta/pedidos'
    | '/_store/conta/perfil'
    | '/_store/conta/privacidade'
    | '/_store/conta/suporte'
    | '/_store/conta/trocas'
    | '/_store/destaques/$slug'
    | '/_store/gift-card/$claimToken'
    | '/_store/politicas/$slug'
    | '/_store/produto/$slug'
    | '/admin/configuracoes/loja'
    | '/_store/conta/'
    | '/_store/conta/conversas/$id'
    | '/_store/conta/pedidos/$id'
    | '/_store/pedido/$publicToken/confirmacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/trocas-e-devolucoes': {
      id: '/_store/trocas-e-devolucoes'
      path: '/trocas-e-devolucoes'
      fullPath: '/trocas-e-devolucoes'
      preLoaderRoute: typeof StoreTrocasEDevolucoesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/termos': {
      id: '/_store/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof StoreTermosRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/stories': {
      id: '/_store/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoreStoriesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/recuperar-senha': {
      id: '/_store/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof StoreRecuperarSenhaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/promocoes': {
      id: '/_store/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof StorePromocoesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/privacidade': {
      id: '/_store/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof StorePrivacidadeRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/perfil-da-loja': {
      id: '/_store/perfil-da-loja'
      path: '/perfil-da-loja'
      fullPath: '/perfil-da-loja'
      preLoaderRoute: typeof StorePerfilDaLojaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/links': {
      id: '/_store/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof StoreLinksRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/instalar': {
      id: '/_store/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof StoreInstalarRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/faq': {
      id: '/_store/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof StoreFaqRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/entrar': {
      id: '/_store/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof StoreEntrarRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/contato': {
      id: '/_store/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof StoreContatoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/conta': {
      id: '/_store/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof StoreContaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/catalogo': {
      id: '/_store/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof StoreCatalogoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/carrinho': {
      id: '/_store/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof StoreCarrinhoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cadastro': {
      id: '/_store/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof StoreCadastroRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/buscar': {
      id: '/_store/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof StoreBuscarRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/conta/': {
      id: '/_store/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof StoreContaIndexRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/admin/configuracoes/loja': {
      id: '/admin/configuracoes/loja'
      path: '/configuracoes/loja'
      fullPath: '/admin/configuracoes/loja'
      preLoaderRoute: typeof AdminConfiguracoesLojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/produto/$slug': {
      id: '/_store/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof StoreProdutoSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/politicas/$slug': {
      id: '/_store/politicas/$slug'
      path: '/politicas/$slug'
      fullPath: '/politicas/$slug'
      preLoaderRoute: typeof StorePoliticasSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/gift-card/$claimToken': {
      id: '/_store/gift-card/$claimToken'
      path: '/gift-card/$claimToken'
      fullPath: '/gift-card/$claimToken'
      preLoaderRoute: typeof StoreGiftCardClaimTokenRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/destaques/$slug': {
      id: '/_store/destaques/$slug'
      path: '/destaques/$slug'
      fullPath: '/destaques/$slug'
      preLoaderRoute: typeof StoreDestaquesSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/conta/trocas': {
      id: '/_store/conta/trocas'
      path: '/trocas'
      fullPath: '/conta/trocas'
      preLoaderRoute: typeof StoreContaTrocasRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/suporte': {
      id: '/_store/conta/suporte'
      path: '/suporte'
      fullPath: '/conta/suporte'
      preLoaderRoute: typeof StoreContaSuporteRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/privacidade': {
      id: '/_store/conta/privacidade'
      path: '/privacidade'
      fullPath: '/conta/privacidade'
      preLoaderRoute: typeof StoreContaPrivacidadeRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/perfil': {
      id: '/_store/conta/perfil'
      path: '/perfil'
      fullPath: '/conta/perfil'
      preLoaderRoute: typeof StoreContaPerfilRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/pedidos': {
      id: '/_store/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof StoreContaPedidosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/pagamentos': {
      id: '/_store/conta/pagamentos'
      path: '/pagamentos'
      fullPath: '/conta/pagamentos'
      preLoaderRoute: typeof StoreContaPagamentosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/gift-cards': {
      id: '/_store/conta/gift-cards'
      path: '/gift-cards'
      fullPath: '/conta/gift-cards'
      preLoaderRoute: typeof StoreContaGiftCardsRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/enderecos': {
      id: '/_store/conta/enderecos'
      path: '/enderecos'
      fullPath: '/conta/enderecos'
      preLoaderRoute: typeof StoreContaEnderecosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/creditos': {
      id: '/_store/conta/creditos'
      path: '/creditos'
      fullPath: '/conta/creditos'
      preLoaderRoute: typeof StoreContaCreditosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/avaliacoes': {
      id: '/_store/conta/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/conta/avaliacoes'
      preLoaderRoute: typeof StoreContaAvaliacoesRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/colecao/$slug': {
      id: '/_store/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof StoreColecaoSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout/revisao': {
      id: '/_store/checkout/revisao'
      path: '/checkout/revisao'
      fullPath: '/checkout/revisao'
      preLoaderRoute: typeof StoreCheckoutRevisaoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout/pagamento': {
      id: '/_store/checkout/pagamento'
      path: '/checkout/pagamento'
      fullPath: '/checkout/pagamento'
      preLoaderRoute: typeof StoreCheckoutPagamentoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout/identificacao': {
      id: '/_store/checkout/identificacao'
      path: '/checkout/identificacao'
      fullPath: '/checkout/identificacao'
      preLoaderRoute: typeof StoreCheckoutIdentificacaoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout/entrega': {
      id: '/_store/checkout/entrega'
      path: '/checkout/entrega'
      fullPath: '/checkout/entrega'
      preLoaderRoute: typeof StoreCheckoutEntregaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout/cotacao': {
      id: '/_store/checkout/cotacao'
      path: '/checkout/cotacao'
      fullPath: '/checkout/cotacao'
      preLoaderRoute: typeof StoreCheckoutCotacaoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/categoria/$slug': {
      id: '/_store/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof StoreCategoriaSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/pedido/$publicToken/confirmacao': {
      id: '/_store/pedido/$publicToken/confirmacao'
      path: '/pedido/$publicToken/confirmacao'
      fullPath: '/pedido/$publicToken/confirmacao'
      preLoaderRoute: typeof StorePedidoPublicTokenConfirmacaoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/conta/pedidos/$id': {
      id: '/_store/conta/pedidos/$id'
      path: '/$id'
      fullPath: '/conta/pedidos/$id'
      preLoaderRoute: typeof StoreContaPedidosIdRouteImport
      parentRoute: typeof StoreContaPedidosRoute
    }
    '/_store/conta/conversas/$id': {
      id: '/_store/conta/conversas/$id'
      path: '/conversas/$id'
      fullPath: '/conta/conversas/$id'
      preLoaderRoute: typeof StoreContaConversasIdRouteImport
      parentRoute: typeof StoreContaRoute
    }
  }
}

interface StoreContaPedidosRouteChildren {
  StoreContaPedidosIdRoute: typeof StoreContaPedidosIdRoute
}

const StoreContaPedidosRouteChildren: StoreContaPedidosRouteChildren = {
  StoreContaPedidosIdRoute: StoreContaPedidosIdRoute,
}

const StoreContaPedidosRouteWithChildren =
  StoreContaPedidosRoute._addFileChildren(StoreContaPedidosRouteChildren)

interface StoreContaRouteChildren {
  StoreContaAvaliacoesRoute: typeof StoreContaAvaliacoesRoute
  StoreContaCreditosRoute: typeof StoreContaCreditosRoute
  StoreContaEnderecosRoute: typeof StoreContaEnderecosRoute
  StoreContaGiftCardsRoute: typeof StoreContaGiftCardsRoute
  StoreContaPagamentosRoute: typeof StoreContaPagamentosRoute
  StoreContaPedidosRoute: typeof StoreContaPedidosRouteWithChildren
  StoreContaPerfilRoute: typeof StoreContaPerfilRoute
  StoreContaPrivacidadeRoute: typeof StoreContaPrivacidadeRoute
  StoreContaSuporteRoute: typeof StoreContaSuporteRoute
  StoreContaTrocasRoute: typeof StoreContaTrocasRoute
  StoreContaIndexRoute: typeof StoreContaIndexRoute
  StoreContaConversasIdRoute: typeof StoreContaConversasIdRoute
}

const StoreContaRouteChildren: StoreContaRouteChildren = {
  StoreContaAvaliacoesRoute: StoreContaAvaliacoesRoute,
  StoreContaCreditosRoute: StoreContaCreditosRoute,
  StoreContaEnderecosRoute: StoreContaEnderecosRoute,
  StoreContaGiftCardsRoute: StoreContaGiftCardsRoute,
  StoreContaPagamentosRoute: StoreContaPagamentosRoute,
  StoreContaPedidosRoute: StoreContaPedidosRouteWithChildren,
  StoreContaPerfilRoute: StoreContaPerfilRoute,
  StoreContaPrivacidadeRoute: StoreContaPrivacidadeRoute,
  StoreContaSuporteRoute: StoreContaSuporteRoute,
  StoreContaTrocasRoute: StoreContaTrocasRoute,
  StoreContaIndexRoute: StoreContaIndexRoute,
  StoreContaConversasIdRoute: StoreContaConversasIdRoute,
}

const StoreContaRouteWithChildren = StoreContaRoute._addFileChildren(
  StoreContaRouteChildren,
)

interface StoreRouteChildren {
  StoreBuscarRoute: typeof StoreBuscarRoute
  StoreCadastroRoute: typeof StoreCadastroRoute
  StoreCarrinhoRoute: typeof StoreCarrinhoRoute
  StoreCatalogoRoute: typeof StoreCatalogoRoute
  StoreContaRoute: typeof StoreContaRouteWithChildren
  StoreContatoRoute: typeof StoreContatoRoute
  StoreEntrarRoute: typeof StoreEntrarRoute
  StoreFaqRoute: typeof StoreFaqRoute
  StoreInstalarRoute: typeof StoreInstalarRoute
  StoreLinksRoute: typeof StoreLinksRoute
  StorePerfilDaLojaRoute: typeof StorePerfilDaLojaRoute
  StorePrivacidadeRoute: typeof StorePrivacidadeRoute
  StorePromocoesRoute: typeof StorePromocoesRoute
  StoreRecuperarSenhaRoute: typeof StoreRecuperarSenhaRoute
  StoreStoriesRoute: typeof StoreStoriesRoute
  StoreTermosRoute: typeof StoreTermosRoute
  StoreTrocasEDevolucoesRoute: typeof StoreTrocasEDevolucoesRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreCategoriaSlugRoute: typeof StoreCategoriaSlugRoute
  StoreCheckoutCotacaoRoute: typeof StoreCheckoutCotacaoRoute
  StoreCheckoutEntregaRoute: typeof StoreCheckoutEntregaRoute
  StoreCheckoutIdentificacaoRoute: typeof StoreCheckoutIdentificacaoRoute
  StoreCheckoutPagamentoRoute: typeof StoreCheckoutPagamentoRoute
  StoreCheckoutRevisaoRoute: typeof StoreCheckoutRevisaoRoute
  StoreColecaoSlugRoute: typeof StoreColecaoSlugRoute
  StoreDestaquesSlugRoute: typeof StoreDestaquesSlugRoute
  StoreGiftCardClaimTokenRoute: typeof StoreGiftCardClaimTokenRoute
  StorePoliticasSlugRoute: typeof StorePoliticasSlugRoute
  StoreProdutoSlugRoute: typeof StoreProdutoSlugRoute
  StorePedidoPublicTokenConfirmacaoRoute: typeof StorePedidoPublicTokenConfirmacaoRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreBuscarRoute: StoreBuscarRoute,
  StoreCadastroRoute: StoreCadastroRoute,
  StoreCarrinhoRoute: StoreCarrinhoRoute,
  StoreCatalogoRoute: StoreCatalogoRoute,
  StoreContaRoute: StoreContaRouteWithChildren,
  StoreContatoRoute: StoreContatoRoute,
  StoreEntrarRoute: StoreEntrarRoute,
  StoreFaqRoute: StoreFaqRoute,
  StoreInstalarRoute: StoreInstalarRoute,
  StoreLinksRoute: StoreLinksRoute,
  StorePerfilDaLojaRoute: StorePerfilDaLojaRoute,
  StorePrivacidadeRoute: StorePrivacidadeRoute,
  StorePromocoesRoute: StorePromocoesRoute,
  StoreRecuperarSenhaRoute: StoreRecuperarSenhaRoute,
  StoreStoriesRoute: StoreStoriesRoute,
  StoreTermosRoute: StoreTermosRoute,
  StoreTrocasEDevolucoesRoute: StoreTrocasEDevolucoesRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreCategoriaSlugRoute: StoreCategoriaSlugRoute,
  StoreCheckoutCotacaoRoute: StoreCheckoutCotacaoRoute,
  StoreCheckoutEntregaRoute: StoreCheckoutEntregaRoute,
  StoreCheckoutIdentificacaoRoute: StoreCheckoutIdentificacaoRoute,
  StoreCheckoutPagamentoRoute: StoreCheckoutPagamentoRoute,
  StoreCheckoutRevisaoRoute: StoreCheckoutRevisaoRoute,
  StoreColecaoSlugRoute: StoreColecaoSlugRoute,
  StoreDestaquesSlugRoute: StoreDestaquesSlugRoute,
  StoreGiftCardClaimTokenRoute: StoreGiftCardClaimTokenRoute,
  StorePoliticasSlugRoute: StorePoliticasSlugRoute,
  StoreProdutoSlugRoute: StoreProdutoSlugRoute,
  StorePedidoPublicTokenConfirmacaoRoute:
    StorePedidoPublicTokenConfirmacaoRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminRouteChildren {
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConfiguracoesLojaRoute: typeof AdminConfiguracoesLojaRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConfiguracoesLojaRoute: AdminConfiguracoesLojaRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
