/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoreIndexRouteImport } from './routes/_store.index'
import { Route as AdminTrocasRouteImport } from './routes/admin.trocas'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminStoriesRouteImport } from './routes/admin.stories'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminPerfilPublicoRouteImport } from './routes/admin.perfil-publico'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminMidiasRouteImport } from './routes/admin.midias'
import { Route as AdminMatchTimeRouteImport } from './routes/admin.match-time'
import { Route as AdminLinkDaBioRouteImport } from './routes/admin.link-da-bio'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminFretesRouteImport } from './routes/admin.fretes'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminDestaquesRouteImport } from './routes/admin.destaques'
import { Route as AdminCriadorRouteImport } from './routes/admin.criador'
import { Route as AdminConversasRouteImport } from './routes/admin.conversas'
import { Route as AdminComprovantesRouteImport } from './routes/admin.comprovantes'
import { Route as AdminComissoesRouteImport } from './routes/admin.comissoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCaixaRouteImport } from './routes/admin.caixa'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'
import { Route as StoreTrocasEDevolucoesRouteImport } from './routes/_store.trocas-e-devolucoes'
import { Route as StoreTermosRouteImport } from './routes/_store.termos'
import { Route as StoreStoriesRouteImport } from './routes/_store.stories'
import { Route as StoreRedefinirSenhaRouteImport } from './routes/_store.redefinir-senha'
import { Route as StoreRecuperarSenhaRouteImport } from './routes/_store.recuperar-senha'
import { Route as StorePromocoesRouteImport } from './routes/_store.promocoes'
import { Route as StorePrivacidadeRouteImport } from './routes/_store.privacidade'
import { Route as StorePerfilDaLojaRouteImport } from './routes/_store.perfil-da-loja'
import { Route as StoreMatchTimeRouteImport } from './routes/_store.match-time'
import { Route as StoreLinksRouteImport } from './routes/_store.links'
import { Route as StoreFaqRouteImport } from './routes/_store.faq'
import { Route as StoreEntrarRouteImport } from './routes/_store.entrar'
import { Route as StoreContatoRouteImport } from './routes/_store.contato'
import { Route as StoreContaRouteImport } from './routes/_store.conta'
import { Route as StoreCheckoutRouteImport } from './routes/_store.checkout'
import { Route as StoreCatalogoRouteImport } from './routes/_store.catalogo'
import { Route as StoreCarrinhoRouteImport } from './routes/_store.carrinho'
import { Route as StoreCadastroRouteImport } from './routes/_store.cadastro'
import { Route as StoreBuscarRouteImport } from './routes/_store.buscar'
import { Route as StoreContaIndexRouteImport } from './routes/_store.conta.index'
import { Route as AdminPedidosTrocasRouteImport } from './routes/admin.pedidos.trocas'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'
import { Route as AdminMarketingNotificacoesRouteImport } from './routes/admin.marketing.notificacoes'
import { Route as AdminMarketingGiftCardsRouteImport } from './routes/admin.marketing.gift-cards'
import { Route as AdminMarketingFeedRouteImport } from './routes/admin.marketing.feed'
import { Route as AdminMarketingCuponsRouteImport } from './routes/admin.marketing.cupons'
import { Route as AdminMarketingCarrinhosRouteImport } from './routes/admin.marketing.carrinhos'
import { Route as AdminFretesTabelasRouteImport } from './routes/admin.fretes.tabelas'
import { Route as AdminFretesCotacoesRouteImport } from './routes/admin.fretes.cotacoes'
import { Route as AdminEstoqueMovimentosRouteImport } from './routes/admin.estoque.movimentos'
import { Route as AdminEstoqueAlertasRouteImport } from './routes/admin.estoque.alertas'
import { Route as AdminConfiguracoesSeoRouteImport } from './routes/admin.configuracoes.seo'
import { Route as AdminConfiguracoesPoliticasRouteImport } from './routes/admin.configuracoes.politicas'
import { Route as AdminConfiguracoesLojaRouteImport } from './routes/admin.configuracoes.loja'
import { Route as AdminConfiguracoesLgpdRouteImport } from './routes/admin.configuracoes.lgpd'
import { Route as AdminConfiguracoesAuditoriaRouteImport } from './routes/admin.configuracoes.auditoria'
import { Route as AdminCmsTemaRouteImport } from './routes/admin.cms.tema'
import { Route as AdminCmsPaginasRouteImport } from './routes/admin.cms.paginas'
import { Route as AdminCmsNavegacaoRouteImport } from './routes/admin.cms.navegacao'
import { Route as AdminClientesIdRouteImport } from './routes/admin.clientes.$id'
import { Route as AdminCatalogoTiposRouteImport } from './routes/admin.catalogo.tipos'
import { Route as AdminCatalogoProdutosRouteImport } from './routes/admin.catalogo.produtos'
import { Route as AdminCatalogoColecoesRouteImport } from './routes/admin.catalogo.colecoes'
import { Route as AdminCatalogoCategoriasRouteImport } from './routes/admin.catalogo.categorias'
import { Route as AdminCatalogoAtributosRouteImport } from './routes/admin.catalogo.atributos'
import { Route as AdminCaixaTurnosRouteImport } from './routes/admin.caixa.turnos'
import { Route as AdminCaixaLancamentosRouteImport } from './routes/admin.caixa.lancamentos'
import { Route as StoreVendedoraSlugRouteImport } from './routes/_store.vendedora.$slug'
import { Route as StoreProdutoSlugRouteImport } from './routes/_store.produto.$slug'
import { Route as StorePoliticasSlugRouteImport } from './routes/_store.politicas.$slug'
import { Route as StorePaginasSlugRouteImport } from './routes/_store.paginas.$slug'
import { Route as StoreGiftCardClaimTokenRouteImport } from './routes/_store.gift-card.$claimToken'
import { Route as StoreDestaquesSlugRouteImport } from './routes/_store.destaques.$slug'
import { Route as StoreContaTrocasRouteImport } from './routes/_store.conta.trocas'
import { Route as StoreContaPerfilRouteImport } from './routes/_store.conta.perfil'
import { Route as StoreContaPedidosRouteImport } from './routes/_store.conta.pedidos'
import { Route as StoreContaPagamentosRouteImport } from './routes/_store.conta.pagamentos'
import { Route as StoreContaGiftCardsRouteImport } from './routes/_store.conta.gift-cards'
import { Route as StoreContaEnderecosRouteImport } from './routes/_store.conta.enderecos'
import { Route as StoreContaCreditosRouteImport } from './routes/_store.conta.creditos'
import { Route as StoreContaAvaliacoesRouteImport } from './routes/_store.conta.avaliacoes'
import { Route as StoreColecaoSlugRouteImport } from './routes/_store.colecao.$slug'
import { Route as StoreCategoriaSlugRouteImport } from './routes/_store.categoria.$slug'
import { Route as AdminPedidosIdReciboRouteImport } from './routes/admin_.pedidos.$id.recibo'
import { Route as AdminCmsPaginasNovoRouteImport } from './routes/admin.cms.paginas.novo'
import { Route as AdminCatalogoProdutosNovoRouteImport } from './routes/admin.catalogo.produtos.novo'
import { Route as AdminCatalogoProdutosIdRouteImport } from './routes/admin.catalogo.produtos.$id'
import { Route as AdminCatalogoColecoesNovoRouteImport } from './routes/admin.catalogo.colecoes.novo'
import { Route as AdminCatalogoCategoriasNovoRouteImport } from './routes/admin.catalogo.categorias.novo'
import { Route as StorePedidoPublicTokenConfirmacaoRouteImport } from './routes/_store.pedido.$publicToken.confirmacao'
import { Route as StoreContaPedidosIdRouteImport } from './routes/_store.conta.pedidos.$id'
import { Route as StoreContaConversasIdRouteImport } from './routes/_store.conta.conversas.$id'
import { Route as AdminCmsPaginasIdEditorRouteImport } from './routes/admin.cms.paginas.$id.editor'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const AdminTrocasRoute = AdminTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoriesRoute = AdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilPublicoRoute = AdminPerfilPublicoRouteImport.update({
  id: '/perfil-publico',
  path: '/perfil-publico',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMidiasRoute = AdminMidiasRouteImport.update({
  id: '/midias',
  path: '/midias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchTimeRoute = AdminMatchTimeRouteImport.update({
  id: '/match-time',
  path: '/match-time',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinkDaBioRoute = AdminLinkDaBioRouteImport.update({
  id: '/link-da-bio',
  path: '/link-da-bio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFretesRoute = AdminFretesRouteImport.update({
  id: '/fretes',
  path: '/fretes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestaquesRoute = AdminDestaquesRouteImport.update({
  id: '/destaques',
  path: '/destaques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCriadorRoute = AdminCriadorRouteImport.update({
  id: '/criador',
  path: '/criador',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversasRoute = AdminConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComprovantesRoute = AdminComprovantesRouteImport.update({
  id: '/comprovantes',
  path: '/comprovantes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComissoesRoute = AdminComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCaixaRoute = AdminCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminRoute,
} as any)
const StoreTrocasEDevolucoesRoute = StoreTrocasEDevolucoesRouteImport.update({
  id: '/trocas-e-devolucoes',
  path: '/trocas-e-devolucoes',
  getParentRoute: () => StoreRoute,
} as any)
const StoreTermosRoute = StoreTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => StoreRoute,
} as any)
const StoreStoriesRoute = StoreStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRedefinirSenhaRoute = StoreRedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRecuperarSenhaRoute = StoreRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => StoreRoute,
} as any)
const StorePromocoesRoute = StorePromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => StoreRoute,
} as any)
const StorePrivacidadeRoute = StorePrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => StoreRoute,
} as any)
const StorePerfilDaLojaRoute = StorePerfilDaLojaRouteImport.update({
  id: '/perfil-da-loja',
  path: '/perfil-da-loja',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMatchTimeRoute = StoreMatchTimeRouteImport.update({
  id: '/match-time',
  path: '/match-time',
  getParentRoute: () => StoreRoute,
} as any)
const StoreLinksRoute = StoreLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => StoreRoute,
} as any)
const StoreFaqRoute = StoreFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => StoreRoute,
} as any)
const StoreEntrarRoute = StoreEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContatoRoute = StoreContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContaRoute = StoreContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCatalogoRoute = StoreCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCarrinhoRoute = StoreCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCadastroRoute = StoreCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => StoreRoute,
} as any)
const StoreBuscarRoute = StoreBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContaIndexRoute = StoreContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreContaRoute,
} as any)
const AdminPedidosTrocasRoute = AdminPedidosTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const AdminMarketingNotificacoesRoute =
  AdminMarketingNotificacoesRouteImport.update({
    id: '/marketing/notificacoes',
    path: '/marketing/notificacoes',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingGiftCardsRoute = AdminMarketingGiftCardsRouteImport.update({
  id: '/marketing/gift-cards',
  path: '/marketing/gift-cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingFeedRoute = AdminMarketingFeedRouteImport.update({
  id: '/marketing/feed',
  path: '/marketing/feed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingCuponsRoute = AdminMarketingCuponsRouteImport.update({
  id: '/marketing/cupons',
  path: '/marketing/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingCarrinhosRoute = AdminMarketingCarrinhosRouteImport.update({
  id: '/marketing/carrinhos',
  path: '/marketing/carrinhos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFretesTabelasRoute = AdminFretesTabelasRouteImport.update({
  id: '/tabelas',
  path: '/tabelas',
  getParentRoute: () => AdminFretesRoute,
} as any)
const AdminFretesCotacoesRoute = AdminFretesCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AdminFretesRoute,
} as any)
const AdminEstoqueMovimentosRoute = AdminEstoqueMovimentosRouteImport.update({
  id: '/movimentos',
  path: '/movimentos',
  getParentRoute: () => AdminEstoqueRoute,
} as any)
const AdminEstoqueAlertasRoute = AdminEstoqueAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminEstoqueRoute,
} as any)
const AdminConfiguracoesSeoRoute = AdminConfiguracoesSeoRouteImport.update({
  id: '/configuracoes/seo',
  path: '/configuracoes/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesPoliticasRoute =
  AdminConfiguracoesPoliticasRouteImport.update({
    id: '/configuracoes/politicas',
    path: '/configuracoes/politicas',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfiguracoesLojaRoute = AdminConfiguracoesLojaRouteImport.update({
  id: '/configuracoes/loja',
  path: '/configuracoes/loja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesLgpdRoute = AdminConfiguracoesLgpdRouteImport.update({
  id: '/configuracoes/lgpd',
  path: '/configuracoes/lgpd',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesAuditoriaRoute =
  AdminConfiguracoesAuditoriaRouteImport.update({
    id: '/configuracoes/auditoria',
    path: '/configuracoes/auditoria',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCmsTemaRoute = AdminCmsTemaRouteImport.update({
  id: '/cms/tema',
  path: '/cms/tema',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsPaginasRoute = AdminCmsPaginasRouteImport.update({
  id: '/cms/paginas',
  path: '/cms/paginas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsNavegacaoRoute = AdminCmsNavegacaoRouteImport.update({
  id: '/cms/navegacao',
  path: '/cms/navegacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIdRoute = AdminClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClientesRoute,
} as any)
const AdminCatalogoTiposRoute = AdminCatalogoTiposRouteImport.update({
  id: '/catalogo/tipos',
  path: '/catalogo/tipos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogoProdutosRoute = AdminCatalogoProdutosRouteImport.update({
  id: '/catalogo/produtos',
  path: '/catalogo/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogoColecoesRoute = AdminCatalogoColecoesRouteImport.update({
  id: '/catalogo/colecoes',
  path: '/catalogo/colecoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogoCategoriasRoute = AdminCatalogoCategoriasRouteImport.update({
  id: '/catalogo/categorias',
  path: '/catalogo/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogoAtributosRoute = AdminCatalogoAtributosRouteImport.update({
  id: '/catalogo/atributos',
  path: '/catalogo/atributos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCaixaTurnosRoute = AdminCaixaTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => AdminCaixaRoute,
} as any)
const AdminCaixaLancamentosRoute = AdminCaixaLancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => AdminCaixaRoute,
} as any)
const StoreVendedoraSlugRoute = StoreVendedoraSlugRouteImport.update({
  id: '/vendedora/$slug',
  path: '/vendedora/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProdutoSlugRoute = StoreProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StorePoliticasSlugRoute = StorePoliticasSlugRouteImport.update({
  id: '/politicas/$slug',
  path: '/politicas/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StorePaginasSlugRoute = StorePaginasSlugRouteImport.update({
  id: '/paginas/$slug',
  path: '/paginas/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreGiftCardClaimTokenRoute = StoreGiftCardClaimTokenRouteImport.update({
  id: '/gift-card/$claimToken',
  path: '/gift-card/$claimToken',
  getParentRoute: () => StoreRoute,
} as any)
const StoreDestaquesSlugRoute = StoreDestaquesSlugRouteImport.update({
  id: '/destaques/$slug',
  path: '/destaques/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContaTrocasRoute = StoreContaTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPerfilRoute = StoreContaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPedidosRoute = StoreContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPagamentosRoute = StoreContaPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaGiftCardsRoute = StoreContaGiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaEnderecosRoute = StoreContaEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaCreditosRoute = StoreContaCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaAvaliacoesRoute = StoreContaAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreColecaoSlugRoute = StoreColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCategoriaSlugRoute = StoreCategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const AdminPedidosIdReciboRoute = AdminPedidosIdReciboRouteImport.update({
  id: '/admin_/pedidos/$id/recibo',
  path: '/admin/pedidos/$id/recibo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsPaginasNovoRoute = AdminCmsPaginasNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminCmsPaginasRoute,
} as any)
const AdminCatalogoProdutosNovoRoute =
  AdminCatalogoProdutosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AdminCatalogoProdutosRoute,
  } as any)
const AdminCatalogoProdutosIdRoute = AdminCatalogoProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCatalogoProdutosRoute,
} as any)
const AdminCatalogoColecoesNovoRoute =
  AdminCatalogoColecoesNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AdminCatalogoColecoesRoute,
  } as any)
const AdminCatalogoCategoriasNovoRoute =
  AdminCatalogoCategoriasNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AdminCatalogoCategoriasRoute,
  } as any)
const StorePedidoPublicTokenConfirmacaoRoute =
  StorePedidoPublicTokenConfirmacaoRouteImport.update({
    id: '/pedido/$publicToken/confirmacao',
    path: '/pedido/$publicToken/confirmacao',
    getParentRoute: () => StoreRoute,
  } as any)
const StoreContaPedidosIdRoute = StoreContaPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoreContaPedidosRoute,
} as any)
const StoreContaConversasIdRoute = StoreContaConversasIdRouteImport.update({
  id: '/conversas/$id',
  path: '/conversas/$id',
  getParentRoute: () => StoreContaRoute,
} as any)
const AdminCmsPaginasIdEditorRoute = AdminCmsPaginasIdEditorRouteImport.update({
  id: '/$id/editor',
  path: '/$id/editor',
  getParentRoute: () => AdminCmsPaginasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/buscar': typeof StoreBuscarRoute
  '/cadastro': typeof StoreCadastroRoute
  '/carrinho': typeof StoreCarrinhoRoute
  '/catalogo': typeof StoreCatalogoRoute
  '/checkout': typeof StoreCheckoutRoute
  '/conta': typeof StoreContaRouteWithChildren
  '/contato': typeof StoreContatoRoute
  '/entrar': typeof StoreEntrarRoute
  '/faq': typeof StoreFaqRoute
  '/links': typeof StoreLinksRoute
  '/match-time': typeof StoreMatchTimeRoute
  '/perfil-da-loja': typeof StorePerfilDaLojaRoute
  '/privacidade': typeof StorePrivacidadeRoute
  '/promocoes': typeof StorePromocoesRoute
  '/recuperar-senha': typeof StoreRecuperarSenhaRoute
  '/redefinir-senha': typeof StoreRedefinirSenhaRoute
  '/stories': typeof StoreStoriesRoute
  '/termos': typeof StoreTermosRoute
  '/trocas-e-devolucoes': typeof StoreTrocasEDevolucoesRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/caixa': typeof AdminCaixaRouteWithChildren
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/comissoes': typeof AdminComissoesRoute
  '/admin/comprovantes': typeof AdminComprovantesRoute
  '/admin/conversas': typeof AdminConversasRoute
  '/admin/criador': typeof AdminCriadorRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/estoque': typeof AdminEstoqueRouteWithChildren
  '/admin/fretes': typeof AdminFretesRouteWithChildren
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/link-da-bio': typeof AdminLinkDaBioRoute
  '/admin/match-time': typeof AdminMatchTimeRoute
  '/admin/midias': typeof AdminMidiasRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/perfil-publico': typeof AdminPerfilPublicoRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/trocas': typeof AdminTrocasRoute
  '/admin/': typeof AdminIndexRoute
  '/categoria/$slug': typeof StoreCategoriaSlugRoute
  '/colecao/$slug': typeof StoreColecaoSlugRoute
  '/conta/avaliacoes': typeof StoreContaAvaliacoesRoute
  '/conta/creditos': typeof StoreContaCreditosRoute
  '/conta/enderecos': typeof StoreContaEnderecosRoute
  '/conta/gift-cards': typeof StoreContaGiftCardsRoute
  '/conta/pagamentos': typeof StoreContaPagamentosRoute
  '/conta/pedidos': typeof StoreContaPedidosRouteWithChildren
  '/conta/perfil': typeof StoreContaPerfilRoute
  '/conta/trocas': typeof StoreContaTrocasRoute
  '/destaques/$slug': typeof StoreDestaquesSlugRoute
  '/gift-card/$claimToken': typeof StoreGiftCardClaimTokenRoute
  '/paginas/$slug': typeof StorePaginasSlugRoute
  '/politicas/$slug': typeof StorePoliticasSlugRoute
  '/produto/$slug': typeof StoreProdutoSlugRoute
  '/vendedora/$slug': typeof StoreVendedoraSlugRoute
  '/admin/caixa/lancamentos': typeof AdminCaixaLancamentosRoute
  '/admin/caixa/turnos': typeof AdminCaixaTurnosRoute
  '/admin/catalogo/atributos': typeof AdminCatalogoAtributosRoute
  '/admin/catalogo/categorias': typeof AdminCatalogoCategoriasRouteWithChildren
  '/admin/catalogo/colecoes': typeof AdminCatalogoColecoesRouteWithChildren
  '/admin/catalogo/produtos': typeof AdminCatalogoProdutosRouteWithChildren
  '/admin/catalogo/tipos': typeof AdminCatalogoTiposRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/cms/navegacao': typeof AdminCmsNavegacaoRoute
  '/admin/cms/paginas': typeof AdminCmsPaginasRouteWithChildren
  '/admin/cms/tema': typeof AdminCmsTemaRoute
  '/admin/configuracoes/auditoria': typeof AdminConfiguracoesAuditoriaRoute
  '/admin/configuracoes/lgpd': typeof AdminConfiguracoesLgpdRoute
  '/admin/configuracoes/loja': typeof AdminConfiguracoesLojaRoute
  '/admin/configuracoes/politicas': typeof AdminConfiguracoesPoliticasRoute
  '/admin/configuracoes/seo': typeof AdminConfiguracoesSeoRoute
  '/admin/estoque/alertas': typeof AdminEstoqueAlertasRoute
  '/admin/estoque/movimentos': typeof AdminEstoqueMovimentosRoute
  '/admin/fretes/cotacoes': typeof AdminFretesCotacoesRoute
  '/admin/fretes/tabelas': typeof AdminFretesTabelasRoute
  '/admin/marketing/carrinhos': typeof AdminMarketingCarrinhosRoute
  '/admin/marketing/cupons': typeof AdminMarketingCuponsRoute
  '/admin/marketing/feed': typeof AdminMarketingFeedRoute
  '/admin/marketing/gift-cards': typeof AdminMarketingGiftCardsRoute
  '/admin/marketing/notificacoes': typeof AdminMarketingNotificacoesRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/trocas': typeof AdminPedidosTrocasRoute
  '/conta/': typeof StoreContaIndexRoute
  '/conta/conversas/$id': typeof StoreContaConversasIdRoute
  '/conta/pedidos/$id': typeof StoreContaPedidosIdRoute
  '/pedido/$publicToken/confirmacao': typeof StorePedidoPublicTokenConfirmacaoRoute
  '/admin/catalogo/categorias/novo': typeof AdminCatalogoCategoriasNovoRoute
  '/admin/catalogo/colecoes/novo': typeof AdminCatalogoColecoesNovoRoute
  '/admin/catalogo/produtos/$id': typeof AdminCatalogoProdutosIdRoute
  '/admin/catalogo/produtos/novo': typeof AdminCatalogoProdutosNovoRoute
  '/admin/cms/paginas/novo': typeof AdminCmsPaginasNovoRoute
  '/admin/pedidos/$id/recibo': typeof AdminPedidosIdReciboRoute
  '/admin/cms/paginas/$id/editor': typeof AdminCmsPaginasIdEditorRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/buscar': typeof StoreBuscarRoute
  '/cadastro': typeof StoreCadastroRoute
  '/carrinho': typeof StoreCarrinhoRoute
  '/catalogo': typeof StoreCatalogoRoute
  '/checkout': typeof StoreCheckoutRoute
  '/contato': typeof StoreContatoRoute
  '/entrar': typeof StoreEntrarRoute
  '/faq': typeof StoreFaqRoute
  '/links': typeof StoreLinksRoute
  '/match-time': typeof StoreMatchTimeRoute
  '/perfil-da-loja': typeof StorePerfilDaLojaRoute
  '/privacidade': typeof StorePrivacidadeRoute
  '/promocoes': typeof StorePromocoesRoute
  '/recuperar-senha': typeof StoreRecuperarSenhaRoute
  '/redefinir-senha': typeof StoreRedefinirSenhaRoute
  '/stories': typeof StoreStoriesRoute
  '/termos': typeof StoreTermosRoute
  '/trocas-e-devolucoes': typeof StoreTrocasEDevolucoesRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/caixa': typeof AdminCaixaRouteWithChildren
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/comissoes': typeof AdminComissoesRoute
  '/admin/comprovantes': typeof AdminComprovantesRoute
  '/admin/conversas': typeof AdminConversasRoute
  '/admin/criador': typeof AdminCriadorRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/estoque': typeof AdminEstoqueRouteWithChildren
  '/admin/fretes': typeof AdminFretesRouteWithChildren
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/link-da-bio': typeof AdminLinkDaBioRoute
  '/admin/match-time': typeof AdminMatchTimeRoute
  '/admin/midias': typeof AdminMidiasRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/perfil-publico': typeof AdminPerfilPublicoRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/trocas': typeof AdminTrocasRoute
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminIndexRoute
  '/categoria/$slug': typeof StoreCategoriaSlugRoute
  '/colecao/$slug': typeof StoreColecaoSlugRoute
  '/conta/avaliacoes': typeof StoreContaAvaliacoesRoute
  '/conta/creditos': typeof StoreContaCreditosRoute
  '/conta/enderecos': typeof StoreContaEnderecosRoute
  '/conta/gift-cards': typeof StoreContaGiftCardsRoute
  '/conta/pagamentos': typeof StoreContaPagamentosRoute
  '/conta/pedidos': typeof StoreContaPedidosRouteWithChildren
  '/conta/perfil': typeof StoreContaPerfilRoute
  '/conta/trocas': typeof StoreContaTrocasRoute
  '/destaques/$slug': typeof StoreDestaquesSlugRoute
  '/gift-card/$claimToken': typeof StoreGiftCardClaimTokenRoute
  '/paginas/$slug': typeof StorePaginasSlugRoute
  '/politicas/$slug': typeof StorePoliticasSlugRoute
  '/produto/$slug': typeof StoreProdutoSlugRoute
  '/vendedora/$slug': typeof StoreVendedoraSlugRoute
  '/admin/caixa/lancamentos': typeof AdminCaixaLancamentosRoute
  '/admin/caixa/turnos': typeof AdminCaixaTurnosRoute
  '/admin/catalogo/atributos': typeof AdminCatalogoAtributosRoute
  '/admin/catalogo/categorias': typeof AdminCatalogoCategoriasRouteWithChildren
  '/admin/catalogo/colecoes': typeof AdminCatalogoColecoesRouteWithChildren
  '/admin/catalogo/produtos': typeof AdminCatalogoProdutosRouteWithChildren
  '/admin/catalogo/tipos': typeof AdminCatalogoTiposRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/cms/navegacao': typeof AdminCmsNavegacaoRoute
  '/admin/cms/paginas': typeof AdminCmsPaginasRouteWithChildren
  '/admin/cms/tema': typeof AdminCmsTemaRoute
  '/admin/configuracoes/auditoria': typeof AdminConfiguracoesAuditoriaRoute
  '/admin/configuracoes/lgpd': typeof AdminConfiguracoesLgpdRoute
  '/admin/configuracoes/loja': typeof AdminConfiguracoesLojaRoute
  '/admin/configuracoes/politicas': typeof AdminConfiguracoesPoliticasRoute
  '/admin/configuracoes/seo': typeof AdminConfiguracoesSeoRoute
  '/admin/estoque/alertas': typeof AdminEstoqueAlertasRoute
  '/admin/estoque/movimentos': typeof AdminEstoqueMovimentosRoute
  '/admin/fretes/cotacoes': typeof AdminFretesCotacoesRoute
  '/admin/fretes/tabelas': typeof AdminFretesTabelasRoute
  '/admin/marketing/carrinhos': typeof AdminMarketingCarrinhosRoute
  '/admin/marketing/cupons': typeof AdminMarketingCuponsRoute
  '/admin/marketing/feed': typeof AdminMarketingFeedRoute
  '/admin/marketing/gift-cards': typeof AdminMarketingGiftCardsRoute
  '/admin/marketing/notificacoes': typeof AdminMarketingNotificacoesRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/trocas': typeof AdminPedidosTrocasRoute
  '/conta': typeof StoreContaIndexRoute
  '/conta/conversas/$id': typeof StoreContaConversasIdRoute
  '/conta/pedidos/$id': typeof StoreContaPedidosIdRoute
  '/pedido/$publicToken/confirmacao': typeof StorePedidoPublicTokenConfirmacaoRoute
  '/admin/catalogo/categorias/novo': typeof AdminCatalogoCategoriasNovoRoute
  '/admin/catalogo/colecoes/novo': typeof AdminCatalogoColecoesNovoRoute
  '/admin/catalogo/produtos/$id': typeof AdminCatalogoProdutosIdRoute
  '/admin/catalogo/produtos/novo': typeof AdminCatalogoProdutosNovoRoute
  '/admin/cms/paginas/novo': typeof AdminCmsPaginasNovoRoute
  '/admin/pedidos/$id/recibo': typeof AdminPedidosIdReciboRoute
  '/admin/cms/paginas/$id/editor': typeof AdminCmsPaginasIdEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_store/buscar': typeof StoreBuscarRoute
  '/_store/cadastro': typeof StoreCadastroRoute
  '/_store/carrinho': typeof StoreCarrinhoRoute
  '/_store/catalogo': typeof StoreCatalogoRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/conta': typeof StoreContaRouteWithChildren
  '/_store/contato': typeof StoreContatoRoute
  '/_store/entrar': typeof StoreEntrarRoute
  '/_store/faq': typeof StoreFaqRoute
  '/_store/links': typeof StoreLinksRoute
  '/_store/match-time': typeof StoreMatchTimeRoute
  '/_store/perfil-da-loja': typeof StorePerfilDaLojaRoute
  '/_store/privacidade': typeof StorePrivacidadeRoute
  '/_store/promocoes': typeof StorePromocoesRoute
  '/_store/recuperar-senha': typeof StoreRecuperarSenhaRoute
  '/_store/redefinir-senha': typeof StoreRedefinirSenhaRoute
  '/_store/stories': typeof StoreStoriesRoute
  '/_store/termos': typeof StoreTermosRoute
  '/_store/trocas-e-devolucoes': typeof StoreTrocasEDevolucoesRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/caixa': typeof AdminCaixaRouteWithChildren
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/comissoes': typeof AdminComissoesRoute
  '/admin/comprovantes': typeof AdminComprovantesRoute
  '/admin/conversas': typeof AdminConversasRoute
  '/admin/criador': typeof AdminCriadorRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/estoque': typeof AdminEstoqueRouteWithChildren
  '/admin/fretes': typeof AdminFretesRouteWithChildren
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/link-da-bio': typeof AdminLinkDaBioRoute
  '/admin/match-time': typeof AdminMatchTimeRoute
  '/admin/midias': typeof AdminMidiasRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/perfil-publico': typeof AdminPerfilPublicoRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/trocas': typeof AdminTrocasRoute
  '/_store/': typeof StoreIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_store/categoria/$slug': typeof StoreCategoriaSlugRoute
  '/_store/colecao/$slug': typeof StoreColecaoSlugRoute
  '/_store/conta/avaliacoes': typeof StoreContaAvaliacoesRoute
  '/_store/conta/creditos': typeof StoreContaCreditosRoute
  '/_store/conta/enderecos': typeof StoreContaEnderecosRoute
  '/_store/conta/gift-cards': typeof StoreContaGiftCardsRoute
  '/_store/conta/pagamentos': typeof StoreContaPagamentosRoute
  '/_store/conta/pedidos': typeof StoreContaPedidosRouteWithChildren
  '/_store/conta/perfil': typeof StoreContaPerfilRoute
  '/_store/conta/trocas': typeof StoreContaTrocasRoute
  '/_store/destaques/$slug': typeof StoreDestaquesSlugRoute
  '/_store/gift-card/$claimToken': typeof StoreGiftCardClaimTokenRoute
  '/_store/paginas/$slug': typeof StorePaginasSlugRoute
  '/_store/politicas/$slug': typeof StorePoliticasSlugRoute
  '/_store/produto/$slug': typeof StoreProdutoSlugRoute
  '/_store/vendedora/$slug': typeof StoreVendedoraSlugRoute
  '/admin/caixa/lancamentos': typeof AdminCaixaLancamentosRoute
  '/admin/caixa/turnos': typeof AdminCaixaTurnosRoute
  '/admin/catalogo/atributos': typeof AdminCatalogoAtributosRoute
  '/admin/catalogo/categorias': typeof AdminCatalogoCategoriasRouteWithChildren
  '/admin/catalogo/colecoes': typeof AdminCatalogoColecoesRouteWithChildren
  '/admin/catalogo/produtos': typeof AdminCatalogoProdutosRouteWithChildren
  '/admin/catalogo/tipos': typeof AdminCatalogoTiposRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/cms/navegacao': typeof AdminCmsNavegacaoRoute
  '/admin/cms/paginas': typeof AdminCmsPaginasRouteWithChildren
  '/admin/cms/tema': typeof AdminCmsTemaRoute
  '/admin/configuracoes/auditoria': typeof AdminConfiguracoesAuditoriaRoute
  '/admin/configuracoes/lgpd': typeof AdminConfiguracoesLgpdRoute
  '/admin/configuracoes/loja': typeof AdminConfiguracoesLojaRoute
  '/admin/configuracoes/politicas': typeof AdminConfiguracoesPoliticasRoute
  '/admin/configuracoes/seo': typeof AdminConfiguracoesSeoRoute
  '/admin/estoque/alertas': typeof AdminEstoqueAlertasRoute
  '/admin/estoque/movimentos': typeof AdminEstoqueMovimentosRoute
  '/admin/fretes/cotacoes': typeof AdminFretesCotacoesRoute
  '/admin/fretes/tabelas': typeof AdminFretesTabelasRoute
  '/admin/marketing/carrinhos': typeof AdminMarketingCarrinhosRoute
  '/admin/marketing/cupons': typeof AdminMarketingCuponsRoute
  '/admin/marketing/feed': typeof AdminMarketingFeedRoute
  '/admin/marketing/gift-cards': typeof AdminMarketingGiftCardsRoute
  '/admin/marketing/notificacoes': typeof AdminMarketingNotificacoesRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/trocas': typeof AdminPedidosTrocasRoute
  '/_store/conta/': typeof StoreContaIndexRoute
  '/_store/conta/conversas/$id': typeof StoreContaConversasIdRoute
  '/_store/conta/pedidos/$id': typeof StoreContaPedidosIdRoute
  '/_store/pedido/$publicToken/confirmacao': typeof StorePedidoPublicTokenConfirmacaoRoute
  '/admin/catalogo/categorias/novo': typeof AdminCatalogoCategoriasNovoRoute
  '/admin/catalogo/colecoes/novo': typeof AdminCatalogoColecoesNovoRoute
  '/admin/catalogo/produtos/$id': typeof AdminCatalogoProdutosIdRoute
  '/admin/catalogo/produtos/novo': typeof AdminCatalogoProdutosNovoRoute
  '/admin/cms/paginas/novo': typeof AdminCmsPaginasNovoRoute
  '/admin_/pedidos/$id/recibo': typeof AdminPedidosIdReciboRoute
  '/admin/cms/paginas/$id/editor': typeof AdminCmsPaginasIdEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/entrar'
    | '/faq'
    | '/links'
    | '/match-time'
    | '/perfil-da-loja'
    | '/privacidade'
    | '/promocoes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/stories'
    | '/termos'
    | '/trocas-e-devolucoes'
    | '/admin/avaliacoes'
    | '/admin/caixa'
    | '/admin/clientes'
    | '/admin/comissoes'
    | '/admin/comprovantes'
    | '/admin/conversas'
    | '/admin/criador'
    | '/admin/destaques'
    | '/admin/equipe'
    | '/admin/estoque'
    | '/admin/fretes'
    | '/admin/integracoes'
    | '/admin/link-da-bio'
    | '/admin/match-time'
    | '/admin/midias'
    | '/admin/onboarding'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/perfil-publico'
    | '/admin/relatorios'
    | '/admin/stories'
    | '/admin/suporte'
    | '/admin/trocas'
    | '/admin/'
    | '/categoria/$slug'
    | '/colecao/$slug'
    | '/conta/avaliacoes'
    | '/conta/creditos'
    | '/conta/enderecos'
    | '/conta/gift-cards'
    | '/conta/pagamentos'
    | '/conta/pedidos'
    | '/conta/perfil'
    | '/conta/trocas'
    | '/destaques/$slug'
    | '/gift-card/$claimToken'
    | '/paginas/$slug'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/vendedora/$slug'
    | '/admin/caixa/lancamentos'
    | '/admin/caixa/turnos'
    | '/admin/catalogo/atributos'
    | '/admin/catalogo/categorias'
    | '/admin/catalogo/colecoes'
    | '/admin/catalogo/produtos'
    | '/admin/catalogo/tipos'
    | '/admin/clientes/$id'
    | '/admin/cms/navegacao'
    | '/admin/cms/paginas'
    | '/admin/cms/tema'
    | '/admin/configuracoes/auditoria'
    | '/admin/configuracoes/lgpd'
    | '/admin/configuracoes/loja'
    | '/admin/configuracoes/politicas'
    | '/admin/configuracoes/seo'
    | '/admin/estoque/alertas'
    | '/admin/estoque/movimentos'
    | '/admin/fretes/cotacoes'
    | '/admin/fretes/tabelas'
    | '/admin/marketing/carrinhos'
    | '/admin/marketing/cupons'
    | '/admin/marketing/feed'
    | '/admin/marketing/gift-cards'
    | '/admin/marketing/notificacoes'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/trocas'
    | '/conta/'
    | '/conta/conversas/$id'
    | '/conta/pedidos/$id'
    | '/pedido/$publicToken/confirmacao'
    | '/admin/catalogo/categorias/novo'
    | '/admin/catalogo/colecoes/novo'
    | '/admin/catalogo/produtos/$id'
    | '/admin/catalogo/produtos/novo'
    | '/admin/cms/paginas/novo'
    | '/admin/pedidos/$id/recibo'
    | '/admin/cms/paginas/$id/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/entrar'
    | '/faq'
    | '/links'
    | '/match-time'
    | '/perfil-da-loja'
    | '/privacidade'
    | '/promocoes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/stories'
    | '/termos'
    | '/trocas-e-devolucoes'
    | '/admin/avaliacoes'
    | '/admin/caixa'
    | '/admin/clientes'
    | '/admin/comissoes'
    | '/admin/comprovantes'
    | '/admin/conversas'
    | '/admin/criador'
    | '/admin/destaques'
    | '/admin/equipe'
    | '/admin/estoque'
    | '/admin/fretes'
    | '/admin/integracoes'
    | '/admin/link-da-bio'
    | '/admin/match-time'
    | '/admin/midias'
    | '/admin/onboarding'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/perfil-publico'
    | '/admin/relatorios'
    | '/admin/stories'
    | '/admin/suporte'
    | '/admin/trocas'
    | '/'
    | '/admin'
    | '/categoria/$slug'
    | '/colecao/$slug'
    | '/conta/avaliacoes'
    | '/conta/creditos'
    | '/conta/enderecos'
    | '/conta/gift-cards'
    | '/conta/pagamentos'
    | '/conta/pedidos'
    | '/conta/perfil'
    | '/conta/trocas'
    | '/destaques/$slug'
    | '/gift-card/$claimToken'
    | '/paginas/$slug'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/vendedora/$slug'
    | '/admin/caixa/lancamentos'
    | '/admin/caixa/turnos'
    | '/admin/catalogo/atributos'
    | '/admin/catalogo/categorias'
    | '/admin/catalogo/colecoes'
    | '/admin/catalogo/produtos'
    | '/admin/catalogo/tipos'
    | '/admin/clientes/$id'
    | '/admin/cms/navegacao'
    | '/admin/cms/paginas'
    | '/admin/cms/tema'
    | '/admin/configuracoes/auditoria'
    | '/admin/configuracoes/lgpd'
    | '/admin/configuracoes/loja'
    | '/admin/configuracoes/politicas'
    | '/admin/configuracoes/seo'
    | '/admin/estoque/alertas'
    | '/admin/estoque/movimentos'
    | '/admin/fretes/cotacoes'
    | '/admin/fretes/tabelas'
    | '/admin/marketing/carrinhos'
    | '/admin/marketing/cupons'
    | '/admin/marketing/feed'
    | '/admin/marketing/gift-cards'
    | '/admin/marketing/notificacoes'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/trocas'
    | '/conta'
    | '/conta/conversas/$id'
    | '/conta/pedidos/$id'
    | '/pedido/$publicToken/confirmacao'
    | '/admin/catalogo/categorias/novo'
    | '/admin/catalogo/colecoes/novo'
    | '/admin/catalogo/produtos/$id'
    | '/admin/catalogo/produtos/novo'
    | '/admin/cms/paginas/novo'
    | '/admin/pedidos/$id/recibo'
    | '/admin/cms/paginas/$id/editor'
  id:
    | '__root__'
    | '/_store'
    | '/admin'
    | '/sitemap.xml'
    | '/_store/buscar'
    | '/_store/cadastro'
    | '/_store/carrinho'
    | '/_store/catalogo'
    | '/_store/checkout'
    | '/_store/conta'
    | '/_store/contato'
    | '/_store/entrar'
    | '/_store/faq'
    | '/_store/links'
    | '/_store/match-time'
    | '/_store/perfil-da-loja'
    | '/_store/privacidade'
    | '/_store/promocoes'
    | '/_store/recuperar-senha'
    | '/_store/redefinir-senha'
    | '/_store/stories'
    | '/_store/termos'
    | '/_store/trocas-e-devolucoes'
    | '/admin/avaliacoes'
    | '/admin/caixa'
    | '/admin/clientes'
    | '/admin/comissoes'
    | '/admin/comprovantes'
    | '/admin/conversas'
    | '/admin/criador'
    | '/admin/destaques'
    | '/admin/equipe'
    | '/admin/estoque'
    | '/admin/fretes'
    | '/admin/integracoes'
    | '/admin/link-da-bio'
    | '/admin/match-time'
    | '/admin/midias'
    | '/admin/onboarding'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/perfil-publico'
    | '/admin/relatorios'
    | '/admin/stories'
    | '/admin/suporte'
    | '/admin/trocas'
    | '/_store/'
    | '/admin/'
    | '/_store/categoria/$slug'
    | '/_store/colecao/$slug'
    | '/_store/conta/avaliacoes'
    | '/_store/conta/creditos'
    | '/_store/conta/enderecos'
    | '/_store/conta/gift-cards'
    | '/_store/conta/pagamentos'
    | '/_store/conta/pedidos'
    | '/_store/conta/perfil'
    | '/_store/conta/trocas'
    | '/_store/destaques/$slug'
    | '/_store/gift-card/$claimToken'
    | '/_store/paginas/$slug'
    | '/_store/politicas/$slug'
    | '/_store/produto/$slug'
    | '/_store/vendedora/$slug'
    | '/admin/caixa/lancamentos'
    | '/admin/caixa/turnos'
    | '/admin/catalogo/atributos'
    | '/admin/catalogo/categorias'
    | '/admin/catalogo/colecoes'
    | '/admin/catalogo/produtos'
    | '/admin/catalogo/tipos'
    | '/admin/clientes/$id'
    | '/admin/cms/navegacao'
    | '/admin/cms/paginas'
    | '/admin/cms/tema'
    | '/admin/configuracoes/auditoria'
    | '/admin/configuracoes/lgpd'
    | '/admin/configuracoes/loja'
    | '/admin/configuracoes/politicas'
    | '/admin/configuracoes/seo'
    | '/admin/estoque/alertas'
    | '/admin/estoque/movimentos'
    | '/admin/fretes/cotacoes'
    | '/admin/fretes/tabelas'
    | '/admin/marketing/carrinhos'
    | '/admin/marketing/cupons'
    | '/admin/marketing/feed'
    | '/admin/marketing/gift-cards'
    | '/admin/marketing/notificacoes'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/trocas'
    | '/_store/conta/'
    | '/_store/conta/conversas/$id'
    | '/_store/conta/pedidos/$id'
    | '/_store/pedido/$publicToken/confirmacao'
    | '/admin/catalogo/categorias/novo'
    | '/admin/catalogo/colecoes/novo'
    | '/admin/catalogo/produtos/$id'
    | '/admin/catalogo/produtos/novo'
    | '/admin/cms/paginas/novo'
    | '/admin_/pedidos/$id/recibo'
    | '/admin/cms/paginas/$id/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminPedidosIdReciboRoute: typeof AdminPedidosIdReciboRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/trocas': {
      id: '/admin/trocas'
      path: '/trocas'
      fullPath: '/admin/trocas'
      preLoaderRoute: typeof AdminTrocasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminStoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil-publico': {
      id: '/admin/perfil-publico'
      path: '/perfil-publico'
      fullPath: '/admin/perfil-publico'
      preLoaderRoute: typeof AdminPerfilPublicoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/midias': {
      id: '/admin/midias'
      path: '/midias'
      fullPath: '/admin/midias'
      preLoaderRoute: typeof AdminMidiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/match-time': {
      id: '/admin/match-time'
      path: '/match-time'
      fullPath: '/admin/match-time'
      preLoaderRoute: typeof AdminMatchTimeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/link-da-bio': {
      id: '/admin/link-da-bio'
      path: '/link-da-bio'
      fullPath: '/admin/link-da-bio'
      preLoaderRoute: typeof AdminLinkDaBioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fretes': {
      id: '/admin/fretes'
      path: '/fretes'
      fullPath: '/admin/fretes'
      preLoaderRoute: typeof AdminFretesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destaques': {
      id: '/admin/destaques'
      path: '/destaques'
      fullPath: '/admin/destaques'
      preLoaderRoute: typeof AdminDestaquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/criador': {
      id: '/admin/criador'
      path: '/criador'
      fullPath: '/admin/criador'
      preLoaderRoute: typeof AdminCriadorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversas': {
      id: '/admin/conversas'
      path: '/conversas'
      fullPath: '/admin/conversas'
      preLoaderRoute: typeof AdminConversasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comprovantes': {
      id: '/admin/comprovantes'
      path: '/comprovantes'
      fullPath: '/admin/comprovantes'
      preLoaderRoute: typeof AdminComprovantesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comissoes': {
      id: '/admin/comissoes'
      path: '/comissoes'
      fullPath: '/admin/comissoes'
      preLoaderRoute: typeof AdminComissoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/caixa': {
      id: '/admin/caixa'
      path: '/caixa'
      fullPath: '/admin/caixa'
      preLoaderRoute: typeof AdminCaixaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/trocas-e-devolucoes': {
      id: '/_store/trocas-e-devolucoes'
      path: '/trocas-e-devolucoes'
      fullPath: '/trocas-e-devolucoes'
      preLoaderRoute: typeof StoreTrocasEDevolucoesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/termos': {
      id: '/_store/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof StoreTermosRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/stories': {
      id: '/_store/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoreStoriesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/redefinir-senha': {
      id: '/_store/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof StoreRedefinirSenhaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/recuperar-senha': {
      id: '/_store/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof StoreRecuperarSenhaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/promocoes': {
      id: '/_store/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof StorePromocoesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/privacidade': {
      id: '/_store/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof StorePrivacidadeRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/perfil-da-loja': {
      id: '/_store/perfil-da-loja'
      path: '/perfil-da-loja'
      fullPath: '/perfil-da-loja'
      preLoaderRoute: typeof StorePerfilDaLojaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/match-time': {
      id: '/_store/match-time'
      path: '/match-time'
      fullPath: '/match-time'
      preLoaderRoute: typeof StoreMatchTimeRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/links': {
      id: '/_store/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof StoreLinksRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/faq': {
      id: '/_store/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof StoreFaqRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/entrar': {
      id: '/_store/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof StoreEntrarRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/contato': {
      id: '/_store/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof StoreContatoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/conta': {
      id: '/_store/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof StoreContaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/catalogo': {
      id: '/_store/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof StoreCatalogoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/carrinho': {
      id: '/_store/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof StoreCarrinhoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cadastro': {
      id: '/_store/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof StoreCadastroRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/buscar': {
      id: '/_store/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof StoreBuscarRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/conta/': {
      id: '/_store/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof StoreContaIndexRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/admin/pedidos/trocas': {
      id: '/admin/pedidos/trocas'
      path: '/trocas'
      fullPath: '/admin/pedidos/trocas'
      preLoaderRoute: typeof AdminPedidosTrocasRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/admin/marketing/notificacoes': {
      id: '/admin/marketing/notificacoes'
      path: '/marketing/notificacoes'
      fullPath: '/admin/marketing/notificacoes'
      preLoaderRoute: typeof AdminMarketingNotificacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/gift-cards': {
      id: '/admin/marketing/gift-cards'
      path: '/marketing/gift-cards'
      fullPath: '/admin/marketing/gift-cards'
      preLoaderRoute: typeof AdminMarketingGiftCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/feed': {
      id: '/admin/marketing/feed'
      path: '/marketing/feed'
      fullPath: '/admin/marketing/feed'
      preLoaderRoute: typeof AdminMarketingFeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/cupons': {
      id: '/admin/marketing/cupons'
      path: '/marketing/cupons'
      fullPath: '/admin/marketing/cupons'
      preLoaderRoute: typeof AdminMarketingCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/carrinhos': {
      id: '/admin/marketing/carrinhos'
      path: '/marketing/carrinhos'
      fullPath: '/admin/marketing/carrinhos'
      preLoaderRoute: typeof AdminMarketingCarrinhosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fretes/tabelas': {
      id: '/admin/fretes/tabelas'
      path: '/tabelas'
      fullPath: '/admin/fretes/tabelas'
      preLoaderRoute: typeof AdminFretesTabelasRouteImport
      parentRoute: typeof AdminFretesRoute
    }
    '/admin/fretes/cotacoes': {
      id: '/admin/fretes/cotacoes'
      path: '/cotacoes'
      fullPath: '/admin/fretes/cotacoes'
      preLoaderRoute: typeof AdminFretesCotacoesRouteImport
      parentRoute: typeof AdminFretesRoute
    }
    '/admin/estoque/movimentos': {
      id: '/admin/estoque/movimentos'
      path: '/movimentos'
      fullPath: '/admin/estoque/movimentos'
      preLoaderRoute: typeof AdminEstoqueMovimentosRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
    '/admin/estoque/alertas': {
      id: '/admin/estoque/alertas'
      path: '/alertas'
      fullPath: '/admin/estoque/alertas'
      preLoaderRoute: typeof AdminEstoqueAlertasRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
    '/admin/configuracoes/seo': {
      id: '/admin/configuracoes/seo'
      path: '/configuracoes/seo'
      fullPath: '/admin/configuracoes/seo'
      preLoaderRoute: typeof AdminConfiguracoesSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes/politicas': {
      id: '/admin/configuracoes/politicas'
      path: '/configuracoes/politicas'
      fullPath: '/admin/configuracoes/politicas'
      preLoaderRoute: typeof AdminConfiguracoesPoliticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes/loja': {
      id: '/admin/configuracoes/loja'
      path: '/configuracoes/loja'
      fullPath: '/admin/configuracoes/loja'
      preLoaderRoute: typeof AdminConfiguracoesLojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes/lgpd': {
      id: '/admin/configuracoes/lgpd'
      path: '/configuracoes/lgpd'
      fullPath: '/admin/configuracoes/lgpd'
      preLoaderRoute: typeof AdminConfiguracoesLgpdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes/auditoria': {
      id: '/admin/configuracoes/auditoria'
      path: '/configuracoes/auditoria'
      fullPath: '/admin/configuracoes/auditoria'
      preLoaderRoute: typeof AdminConfiguracoesAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/tema': {
      id: '/admin/cms/tema'
      path: '/cms/tema'
      fullPath: '/admin/cms/tema'
      preLoaderRoute: typeof AdminCmsTemaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/paginas': {
      id: '/admin/cms/paginas'
      path: '/cms/paginas'
      fullPath: '/admin/cms/paginas'
      preLoaderRoute: typeof AdminCmsPaginasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/navegacao': {
      id: '/admin/cms/navegacao'
      path: '/cms/navegacao'
      fullPath: '/admin/cms/navegacao'
      preLoaderRoute: typeof AdminCmsNavegacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$id': {
      id: '/admin/clientes/$id'
      path: '/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AdminClientesIdRouteImport
      parentRoute: typeof AdminClientesRoute
    }
    '/admin/catalogo/tipos': {
      id: '/admin/catalogo/tipos'
      path: '/catalogo/tipos'
      fullPath: '/admin/catalogo/tipos'
      preLoaderRoute: typeof AdminCatalogoTiposRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogo/produtos': {
      id: '/admin/catalogo/produtos'
      path: '/catalogo/produtos'
      fullPath: '/admin/catalogo/produtos'
      preLoaderRoute: typeof AdminCatalogoProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogo/colecoes': {
      id: '/admin/catalogo/colecoes'
      path: '/catalogo/colecoes'
      fullPath: '/admin/catalogo/colecoes'
      preLoaderRoute: typeof AdminCatalogoColecoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogo/categorias': {
      id: '/admin/catalogo/categorias'
      path: '/catalogo/categorias'
      fullPath: '/admin/catalogo/categorias'
      preLoaderRoute: typeof AdminCatalogoCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogo/atributos': {
      id: '/admin/catalogo/atributos'
      path: '/catalogo/atributos'
      fullPath: '/admin/catalogo/atributos'
      preLoaderRoute: typeof AdminCatalogoAtributosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/caixa/turnos': {
      id: '/admin/caixa/turnos'
      path: '/turnos'
      fullPath: '/admin/caixa/turnos'
      preLoaderRoute: typeof AdminCaixaTurnosRouteImport
      parentRoute: typeof AdminCaixaRoute
    }
    '/admin/caixa/lancamentos': {
      id: '/admin/caixa/lancamentos'
      path: '/lancamentos'
      fullPath: '/admin/caixa/lancamentos'
      preLoaderRoute: typeof AdminCaixaLancamentosRouteImport
      parentRoute: typeof AdminCaixaRoute
    }
    '/_store/vendedora/$slug': {
      id: '/_store/vendedora/$slug'
      path: '/vendedora/$slug'
      fullPath: '/vendedora/$slug'
      preLoaderRoute: typeof StoreVendedoraSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/produto/$slug': {
      id: '/_store/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof StoreProdutoSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/politicas/$slug': {
      id: '/_store/politicas/$slug'
      path: '/politicas/$slug'
      fullPath: '/politicas/$slug'
      preLoaderRoute: typeof StorePoliticasSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/paginas/$slug': {
      id: '/_store/paginas/$slug'
      path: '/paginas/$slug'
      fullPath: '/paginas/$slug'
      preLoaderRoute: typeof StorePaginasSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/gift-card/$claimToken': {
      id: '/_store/gift-card/$claimToken'
      path: '/gift-card/$claimToken'
      fullPath: '/gift-card/$claimToken'
      preLoaderRoute: typeof StoreGiftCardClaimTokenRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/destaques/$slug': {
      id: '/_store/destaques/$slug'
      path: '/destaques/$slug'
      fullPath: '/destaques/$slug'
      preLoaderRoute: typeof StoreDestaquesSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/conta/trocas': {
      id: '/_store/conta/trocas'
      path: '/trocas'
      fullPath: '/conta/trocas'
      preLoaderRoute: typeof StoreContaTrocasRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/perfil': {
      id: '/_store/conta/perfil'
      path: '/perfil'
      fullPath: '/conta/perfil'
      preLoaderRoute: typeof StoreContaPerfilRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/pedidos': {
      id: '/_store/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof StoreContaPedidosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/pagamentos': {
      id: '/_store/conta/pagamentos'
      path: '/pagamentos'
      fullPath: '/conta/pagamentos'
      preLoaderRoute: typeof StoreContaPagamentosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/gift-cards': {
      id: '/_store/conta/gift-cards'
      path: '/gift-cards'
      fullPath: '/conta/gift-cards'
      preLoaderRoute: typeof StoreContaGiftCardsRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/enderecos': {
      id: '/_store/conta/enderecos'
      path: '/enderecos'
      fullPath: '/conta/enderecos'
      preLoaderRoute: typeof StoreContaEnderecosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/creditos': {
      id: '/_store/conta/creditos'
      path: '/creditos'
      fullPath: '/conta/creditos'
      preLoaderRoute: typeof StoreContaCreditosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/avaliacoes': {
      id: '/_store/conta/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/conta/avaliacoes'
      preLoaderRoute: typeof StoreContaAvaliacoesRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/colecao/$slug': {
      id: '/_store/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof StoreColecaoSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/categoria/$slug': {
      id: '/_store/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof StoreCategoriaSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin_/pedidos/$id/recibo': {
      id: '/admin_/pedidos/$id/recibo'
      path: '/admin/pedidos/$id/recibo'
      fullPath: '/admin/pedidos/$id/recibo'
      preLoaderRoute: typeof AdminPedidosIdReciboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms/paginas/novo': {
      id: '/admin/cms/paginas/novo'
      path: '/novo'
      fullPath: '/admin/cms/paginas/novo'
      preLoaderRoute: typeof AdminCmsPaginasNovoRouteImport
      parentRoute: typeof AdminCmsPaginasRoute
    }
    '/admin/catalogo/produtos/novo': {
      id: '/admin/catalogo/produtos/novo'
      path: '/novo'
      fullPath: '/admin/catalogo/produtos/novo'
      preLoaderRoute: typeof AdminCatalogoProdutosNovoRouteImport
      parentRoute: typeof AdminCatalogoProdutosRoute
    }
    '/admin/catalogo/produtos/$id': {
      id: '/admin/catalogo/produtos/$id'
      path: '/$id'
      fullPath: '/admin/catalogo/produtos/$id'
      preLoaderRoute: typeof AdminCatalogoProdutosIdRouteImport
      parentRoute: typeof AdminCatalogoProdutosRoute
    }
    '/admin/catalogo/colecoes/novo': {
      id: '/admin/catalogo/colecoes/novo'
      path: '/novo'
      fullPath: '/admin/catalogo/colecoes/novo'
      preLoaderRoute: typeof AdminCatalogoColecoesNovoRouteImport
      parentRoute: typeof AdminCatalogoColecoesRoute
    }
    '/admin/catalogo/categorias/novo': {
      id: '/admin/catalogo/categorias/novo'
      path: '/novo'
      fullPath: '/admin/catalogo/categorias/novo'
      preLoaderRoute: typeof AdminCatalogoCategoriasNovoRouteImport
      parentRoute: typeof AdminCatalogoCategoriasRoute
    }
    '/_store/pedido/$publicToken/confirmacao': {
      id: '/_store/pedido/$publicToken/confirmacao'
      path: '/pedido/$publicToken/confirmacao'
      fullPath: '/pedido/$publicToken/confirmacao'
      preLoaderRoute: typeof StorePedidoPublicTokenConfirmacaoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/conta/pedidos/$id': {
      id: '/_store/conta/pedidos/$id'
      path: '/$id'
      fullPath: '/conta/pedidos/$id'
      preLoaderRoute: typeof StoreContaPedidosIdRouteImport
      parentRoute: typeof StoreContaPedidosRoute
    }
    '/_store/conta/conversas/$id': {
      id: '/_store/conta/conversas/$id'
      path: '/conversas/$id'
      fullPath: '/conta/conversas/$id'
      preLoaderRoute: typeof StoreContaConversasIdRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/admin/cms/paginas/$id/editor': {
      id: '/admin/cms/paginas/$id/editor'
      path: '/$id/editor'
      fullPath: '/admin/cms/paginas/$id/editor'
      preLoaderRoute: typeof AdminCmsPaginasIdEditorRouteImport
      parentRoute: typeof AdminCmsPaginasRoute
    }
  }
}

interface StoreContaPedidosRouteChildren {
  StoreContaPedidosIdRoute: typeof StoreContaPedidosIdRoute
}

const StoreContaPedidosRouteChildren: StoreContaPedidosRouteChildren = {
  StoreContaPedidosIdRoute: StoreContaPedidosIdRoute,
}

const StoreContaPedidosRouteWithChildren =
  StoreContaPedidosRoute._addFileChildren(StoreContaPedidosRouteChildren)

interface StoreContaRouteChildren {
  StoreContaAvaliacoesRoute: typeof StoreContaAvaliacoesRoute
  StoreContaCreditosRoute: typeof StoreContaCreditosRoute
  StoreContaEnderecosRoute: typeof StoreContaEnderecosRoute
  StoreContaGiftCardsRoute: typeof StoreContaGiftCardsRoute
  StoreContaPagamentosRoute: typeof StoreContaPagamentosRoute
  StoreContaPedidosRoute: typeof StoreContaPedidosRouteWithChildren
  StoreContaPerfilRoute: typeof StoreContaPerfilRoute
  StoreContaTrocasRoute: typeof StoreContaTrocasRoute
  StoreContaIndexRoute: typeof StoreContaIndexRoute
  StoreContaConversasIdRoute: typeof StoreContaConversasIdRoute
}

const StoreContaRouteChildren: StoreContaRouteChildren = {
  StoreContaAvaliacoesRoute: StoreContaAvaliacoesRoute,
  StoreContaCreditosRoute: StoreContaCreditosRoute,
  StoreContaEnderecosRoute: StoreContaEnderecosRoute,
  StoreContaGiftCardsRoute: StoreContaGiftCardsRoute,
  StoreContaPagamentosRoute: StoreContaPagamentosRoute,
  StoreContaPedidosRoute: StoreContaPedidosRouteWithChildren,
  StoreContaPerfilRoute: StoreContaPerfilRoute,
  StoreContaTrocasRoute: StoreContaTrocasRoute,
  StoreContaIndexRoute: StoreContaIndexRoute,
  StoreContaConversasIdRoute: StoreContaConversasIdRoute,
}

const StoreContaRouteWithChildren = StoreContaRoute._addFileChildren(
  StoreContaRouteChildren,
)

interface StoreRouteChildren {
  StoreBuscarRoute: typeof StoreBuscarRoute
  StoreCadastroRoute: typeof StoreCadastroRoute
  StoreCarrinhoRoute: typeof StoreCarrinhoRoute
  StoreCatalogoRoute: typeof StoreCatalogoRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreContaRoute: typeof StoreContaRouteWithChildren
  StoreContatoRoute: typeof StoreContatoRoute
  StoreEntrarRoute: typeof StoreEntrarRoute
  StoreFaqRoute: typeof StoreFaqRoute
  StoreLinksRoute: typeof StoreLinksRoute
  StoreMatchTimeRoute: typeof StoreMatchTimeRoute
  StorePerfilDaLojaRoute: typeof StorePerfilDaLojaRoute
  StorePrivacidadeRoute: typeof StorePrivacidadeRoute
  StorePromocoesRoute: typeof StorePromocoesRoute
  StoreRecuperarSenhaRoute: typeof StoreRecuperarSenhaRoute
  StoreRedefinirSenhaRoute: typeof StoreRedefinirSenhaRoute
  StoreStoriesRoute: typeof StoreStoriesRoute
  StoreTermosRoute: typeof StoreTermosRoute
  StoreTrocasEDevolucoesRoute: typeof StoreTrocasEDevolucoesRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreCategoriaSlugRoute: typeof StoreCategoriaSlugRoute
  StoreColecaoSlugRoute: typeof StoreColecaoSlugRoute
  StoreDestaquesSlugRoute: typeof StoreDestaquesSlugRoute
  StoreGiftCardClaimTokenRoute: typeof StoreGiftCardClaimTokenRoute
  StorePaginasSlugRoute: typeof StorePaginasSlugRoute
  StorePoliticasSlugRoute: typeof StorePoliticasSlugRoute
  StoreProdutoSlugRoute: typeof StoreProdutoSlugRoute
  StoreVendedoraSlugRoute: typeof StoreVendedoraSlugRoute
  StorePedidoPublicTokenConfirmacaoRoute: typeof StorePedidoPublicTokenConfirmacaoRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreBuscarRoute: StoreBuscarRoute,
  StoreCadastroRoute: StoreCadastroRoute,
  StoreCarrinhoRoute: StoreCarrinhoRoute,
  StoreCatalogoRoute: StoreCatalogoRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreContaRoute: StoreContaRouteWithChildren,
  StoreContatoRoute: StoreContatoRoute,
  StoreEntrarRoute: StoreEntrarRoute,
  StoreFaqRoute: StoreFaqRoute,
  StoreLinksRoute: StoreLinksRoute,
  StoreMatchTimeRoute: StoreMatchTimeRoute,
  StorePerfilDaLojaRoute: StorePerfilDaLojaRoute,
  StorePrivacidadeRoute: StorePrivacidadeRoute,
  StorePromocoesRoute: StorePromocoesRoute,
  StoreRecuperarSenhaRoute: StoreRecuperarSenhaRoute,
  StoreRedefinirSenhaRoute: StoreRedefinirSenhaRoute,
  StoreStoriesRoute: StoreStoriesRoute,
  StoreTermosRoute: StoreTermosRoute,
  StoreTrocasEDevolucoesRoute: StoreTrocasEDevolucoesRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreCategoriaSlugRoute: StoreCategoriaSlugRoute,
  StoreColecaoSlugRoute: StoreColecaoSlugRoute,
  StoreDestaquesSlugRoute: StoreDestaquesSlugRoute,
  StoreGiftCardClaimTokenRoute: StoreGiftCardClaimTokenRoute,
  StorePaginasSlugRoute: StorePaginasSlugRoute,
  StorePoliticasSlugRoute: StorePoliticasSlugRoute,
  StoreProdutoSlugRoute: StoreProdutoSlugRoute,
  StoreVendedoraSlugRoute: StoreVendedoraSlugRoute,
  StorePedidoPublicTokenConfirmacaoRoute:
    StorePedidoPublicTokenConfirmacaoRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminCaixaRouteChildren {
  AdminCaixaLancamentosRoute: typeof AdminCaixaLancamentosRoute
  AdminCaixaTurnosRoute: typeof AdminCaixaTurnosRoute
}

const AdminCaixaRouteChildren: AdminCaixaRouteChildren = {
  AdminCaixaLancamentosRoute: AdminCaixaLancamentosRoute,
  AdminCaixaTurnosRoute: AdminCaixaTurnosRoute,
}

const AdminCaixaRouteWithChildren = AdminCaixaRoute._addFileChildren(
  AdminCaixaRouteChildren,
)

interface AdminClientesRouteChildren {
  AdminClientesIdRoute: typeof AdminClientesIdRoute
}

const AdminClientesRouteChildren: AdminClientesRouteChildren = {
  AdminClientesIdRoute: AdminClientesIdRoute,
}

const AdminClientesRouteWithChildren = AdminClientesRoute._addFileChildren(
  AdminClientesRouteChildren,
)

interface AdminEstoqueRouteChildren {
  AdminEstoqueAlertasRoute: typeof AdminEstoqueAlertasRoute
  AdminEstoqueMovimentosRoute: typeof AdminEstoqueMovimentosRoute
}

const AdminEstoqueRouteChildren: AdminEstoqueRouteChildren = {
  AdminEstoqueAlertasRoute: AdminEstoqueAlertasRoute,
  AdminEstoqueMovimentosRoute: AdminEstoqueMovimentosRoute,
}

const AdminEstoqueRouteWithChildren = AdminEstoqueRoute._addFileChildren(
  AdminEstoqueRouteChildren,
)

interface AdminFretesRouteChildren {
  AdminFretesCotacoesRoute: typeof AdminFretesCotacoesRoute
  AdminFretesTabelasRoute: typeof AdminFretesTabelasRoute
}

const AdminFretesRouteChildren: AdminFretesRouteChildren = {
  AdminFretesCotacoesRoute: AdminFretesCotacoesRoute,
  AdminFretesTabelasRoute: AdminFretesTabelasRoute,
}

const AdminFretesRouteWithChildren = AdminFretesRoute._addFileChildren(
  AdminFretesRouteChildren,
)

interface AdminPedidosRouteChildren {
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminPedidosTrocasRoute: typeof AdminPedidosTrocasRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminPedidosTrocasRoute: AdminPedidosTrocasRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

interface AdminCatalogoCategoriasRouteChildren {
  AdminCatalogoCategoriasNovoRoute: typeof AdminCatalogoCategoriasNovoRoute
}

const AdminCatalogoCategoriasRouteChildren: AdminCatalogoCategoriasRouteChildren =
  {
    AdminCatalogoCategoriasNovoRoute: AdminCatalogoCategoriasNovoRoute,
  }

const AdminCatalogoCategoriasRouteWithChildren =
  AdminCatalogoCategoriasRoute._addFileChildren(
    AdminCatalogoCategoriasRouteChildren,
  )

interface AdminCatalogoColecoesRouteChildren {
  AdminCatalogoColecoesNovoRoute: typeof AdminCatalogoColecoesNovoRoute
}

const AdminCatalogoColecoesRouteChildren: AdminCatalogoColecoesRouteChildren = {
  AdminCatalogoColecoesNovoRoute: AdminCatalogoColecoesNovoRoute,
}

const AdminCatalogoColecoesRouteWithChildren =
  AdminCatalogoColecoesRoute._addFileChildren(
    AdminCatalogoColecoesRouteChildren,
  )

interface AdminCatalogoProdutosRouteChildren {
  AdminCatalogoProdutosIdRoute: typeof AdminCatalogoProdutosIdRoute
  AdminCatalogoProdutosNovoRoute: typeof AdminCatalogoProdutosNovoRoute
}

const AdminCatalogoProdutosRouteChildren: AdminCatalogoProdutosRouteChildren = {
  AdminCatalogoProdutosIdRoute: AdminCatalogoProdutosIdRoute,
  AdminCatalogoProdutosNovoRoute: AdminCatalogoProdutosNovoRoute,
}

const AdminCatalogoProdutosRouteWithChildren =
  AdminCatalogoProdutosRoute._addFileChildren(
    AdminCatalogoProdutosRouteChildren,
  )

interface AdminCmsPaginasRouteChildren {
  AdminCmsPaginasNovoRoute: typeof AdminCmsPaginasNovoRoute
  AdminCmsPaginasIdEditorRoute: typeof AdminCmsPaginasIdEditorRoute
}

const AdminCmsPaginasRouteChildren: AdminCmsPaginasRouteChildren = {
  AdminCmsPaginasNovoRoute: AdminCmsPaginasNovoRoute,
  AdminCmsPaginasIdEditorRoute: AdminCmsPaginasIdEditorRoute,
}

const AdminCmsPaginasRouteWithChildren = AdminCmsPaginasRoute._addFileChildren(
  AdminCmsPaginasRouteChildren,
)

interface AdminRouteChildren {
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminCaixaRoute: typeof AdminCaixaRouteWithChildren
  AdminClientesRoute: typeof AdminClientesRouteWithChildren
  AdminComissoesRoute: typeof AdminComissoesRoute
  AdminComprovantesRoute: typeof AdminComprovantesRoute
  AdminConversasRoute: typeof AdminConversasRoute
  AdminCriadorRoute: typeof AdminCriadorRoute
  AdminDestaquesRoute: typeof AdminDestaquesRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminEstoqueRoute: typeof AdminEstoqueRouteWithChildren
  AdminFretesRoute: typeof AdminFretesRouteWithChildren
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminLinkDaBioRoute: typeof AdminLinkDaBioRoute
  AdminMatchTimeRoute: typeof AdminMatchTimeRoute
  AdminMidiasRoute: typeof AdminMidiasRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminPerfilPublicoRoute: typeof AdminPerfilPublicoRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminStoriesRoute: typeof AdminStoriesRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminTrocasRoute: typeof AdminTrocasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCatalogoAtributosRoute: typeof AdminCatalogoAtributosRoute
  AdminCatalogoCategoriasRoute: typeof AdminCatalogoCategoriasRouteWithChildren
  AdminCatalogoColecoesRoute: typeof AdminCatalogoColecoesRouteWithChildren
  AdminCatalogoProdutosRoute: typeof AdminCatalogoProdutosRouteWithChildren
  AdminCatalogoTiposRoute: typeof AdminCatalogoTiposRoute
  AdminCmsNavegacaoRoute: typeof AdminCmsNavegacaoRoute
  AdminCmsPaginasRoute: typeof AdminCmsPaginasRouteWithChildren
  AdminCmsTemaRoute: typeof AdminCmsTemaRoute
  AdminConfiguracoesAuditoriaRoute: typeof AdminConfiguracoesAuditoriaRoute
  AdminConfiguracoesLgpdRoute: typeof AdminConfiguracoesLgpdRoute
  AdminConfiguracoesLojaRoute: typeof AdminConfiguracoesLojaRoute
  AdminConfiguracoesPoliticasRoute: typeof AdminConfiguracoesPoliticasRoute
  AdminConfiguracoesSeoRoute: typeof AdminConfiguracoesSeoRoute
  AdminMarketingCarrinhosRoute: typeof AdminMarketingCarrinhosRoute
  AdminMarketingCuponsRoute: typeof AdminMarketingCuponsRoute
  AdminMarketingFeedRoute: typeof AdminMarketingFeedRoute
  AdminMarketingGiftCardsRoute: typeof AdminMarketingGiftCardsRoute
  AdminMarketingNotificacoesRoute: typeof AdminMarketingNotificacoesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminCaixaRoute: AdminCaixaRouteWithChildren,
  AdminClientesRoute: AdminClientesRouteWithChildren,
  AdminComissoesRoute: AdminComissoesRoute,
  AdminComprovantesRoute: AdminComprovantesRoute,
  AdminConversasRoute: AdminConversasRoute,
  AdminCriadorRoute: AdminCriadorRoute,
  AdminDestaquesRoute: AdminDestaquesRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminEstoqueRoute: AdminEstoqueRouteWithChildren,
  AdminFretesRoute: AdminFretesRouteWithChildren,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminLinkDaBioRoute: AdminLinkDaBioRoute,
  AdminMatchTimeRoute: AdminMatchTimeRoute,
  AdminMidiasRoute: AdminMidiasRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminPerfilPublicoRoute: AdminPerfilPublicoRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminStoriesRoute: AdminStoriesRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminTrocasRoute: AdminTrocasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCatalogoAtributosRoute: AdminCatalogoAtributosRoute,
  AdminCatalogoCategoriasRoute: AdminCatalogoCategoriasRouteWithChildren,
  AdminCatalogoColecoesRoute: AdminCatalogoColecoesRouteWithChildren,
  AdminCatalogoProdutosRoute: AdminCatalogoProdutosRouteWithChildren,
  AdminCatalogoTiposRoute: AdminCatalogoTiposRoute,
  AdminCmsNavegacaoRoute: AdminCmsNavegacaoRoute,
  AdminCmsPaginasRoute: AdminCmsPaginasRouteWithChildren,
  AdminCmsTemaRoute: AdminCmsTemaRoute,
  AdminConfiguracoesAuditoriaRoute: AdminConfiguracoesAuditoriaRoute,
  AdminConfiguracoesLgpdRoute: AdminConfiguracoesLgpdRoute,
  AdminConfiguracoesLojaRoute: AdminConfiguracoesLojaRoute,
  AdminConfiguracoesPoliticasRoute: AdminConfiguracoesPoliticasRoute,
  AdminConfiguracoesSeoRoute: AdminConfiguracoesSeoRoute,
  AdminMarketingCarrinhosRoute: AdminMarketingCarrinhosRoute,
  AdminMarketingCuponsRoute: AdminMarketingCuponsRoute,
  AdminMarketingFeedRoute: AdminMarketingFeedRoute,
  AdminMarketingGiftCardsRoute: AdminMarketingGiftCardsRoute,
  AdminMarketingNotificacoesRoute: AdminMarketingNotificacoesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminPedidosIdReciboRoute: AdminPedidosIdReciboRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
